customization:
  extraKernelArgs:
    - intel_idle.max_cstate=0
    - intel_iommu=on
    - iommu=pt
    - cpufreq.default_governor=performance
    - nvme_core.io_timeout=255
    - nvme_core.default_ps_max_latency_us=0
  systemExtensions:
    officialExtensions:
      - siderolabs/btrfs
      - siderolabs/crun
      - siderolabs/i915
      - siderolabs/intel-ucode
      - siderolabs/iscsi-tools
      - siderolabs/mei
      - siderolabs/nut-client
      - siderolabs/realtek-firmware
      - siderolabs/wasmedge
      - siderolabs/xe
