# oauth2-proxy-middleware.yaml
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: authelia-forward-auth
spec:
  forwardAuth:
    address: "http://authelia.security.svc.cluster.local:9091/api/authz/forward-auth"
    trustForwardHeader: true
    maxResponseBodySize: 2097152
    authResponseHeaders:
      - "Remote-User"
      - "Remote-Groups"
      - "Remote-Email"
      - "Remote-Name"
