apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: automation
resources:
  - pvc.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - http-route.yaml
  - network-policy.yaml

images:
  - name: binwiederhier/ntfy
    newTag: v2.21.0@sha256:2b9e12d56a538f4402da51328eeca02696c4b207ab7fbe031c27e51a22ca9b86
  - name: alpine
    newTag: 3.23.4@sha256:5b10f432ef3da1b8d4c7eb6c487f2f5a8f096bc91145e68878dd4a5019afde11

configMapGenerator:
  - name: ntfy-config
    files:
      - server.yml.template=template/server.yml

generatorOptions:
  disableNameSuffixHash: true