apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: automation
resources:
  - pvc.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - http-route.yaml
  - rate-limit.yaml
  - network-policy.yaml

images:
  - name: binwiederhier/ntfy
    newTag: v2.26.3@sha256:081b53dbb20674fcfe05fdb4eb8af9036a2645ef979543d16f7f80803af467b1
  - name: alpine
    newTag: 3.24.1@sha256:28bd5fe8b56d1bd048e5babf5b10710ebe0bae67db86916198a6eec434943f8b

configMapGenerator:
  - name: ntfy-config
    files:
      - server.yml.template=template/server.yml

generatorOptions:
  disableNameSuffixHash: true