apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: automation
resources:
  - pvc.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - http-route.yaml
  - rate-limit.yaml
  - network-policy.yaml

images:
  - name: binwiederhier/ntfy
    newTag: v2.25.0@sha256:cfbbb1bac9196cb711e29ef0ac4adaeb033be6235f1df857705dc39c14384a1d
  - name: alpine
    newTag: 3.24.1@sha256:28bd5fe8b56d1bd048e5babf5b10710ebe0bae67db86916198a6eec434943f8b

configMapGenerator:
  - name: ntfy-config
    files:
      - server.yml.template=template/server.yml

generatorOptions:
  disableNameSuffixHash: true