apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ntfy-secret
spec:
  secretStoreRef:
    name: openbao-store
    kind: ClusterSecretStore
  target:
    name: ntfy-secret
  data:
    - secretKey: NTFY_WEB_PUSH_PUBLIC_KEY
      remoteRef:
        key: automation/ntfy
        property: NTFY_WEB_PUSH_PUBLIC_KEY
    - secretKey: NTFY_WEB_PUSH_PRIVATE_KEY
      remoteRef:
        key: automation/ntfy
        property: NTFY_WEB_PUSH_PRIVATE_KEY
    - secretKey: NTFY_WEB_PUSH_EMAIL_ADDRESS
      remoteRef:
        key: automation/ntfy
        property: NTFY_WEB_PUSH_EMAIL_ADDRESS
    ####
    # Generate hash:
    #   docker run --rm -it binwiederhier/ntfy user hash
    # Users separated by commas
    # Format: <username>:<password_hash>:admin
    ####
    - secretKey: NTFY_AUTH_USERS
      remoteRef:
        key: automation/ntfy
        property: NTFY_AUTH_USERS
