apiVersion: v1
kind: Service
metadata:
  name: ntfy
  namespace: monitoring
  labels:
    app.kubernetes.io/name: ntfy
spec:
  ports:
    - port: 80
      targetPort: web-ui
      protocol: TCP
      name: web-ui
  selector:
    app.kubernetes.io/name: ntfy
