apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: mealie-route
spec:
  parentRefs:
    - name: internal-gateway
      namespace: traefik
  hostnames:
    - "recipes.kerrlab.app"
  rules:
    # Rule 1: Static Recipe Photos, Media & Nuxt Bundles (CACHED)
    - matches:
        - path:
            type: PathPrefix
            value: /api/media
        - path:
            type: PathPrefix
            value: /_nuxt
        - path:
            type: PathPrefix
            value: /icons
        - path:
            type: Exact
            value: /favicon.ico
        - path:
            type: Exact
            value: /favicon.svg
        - path:
            type: Exact
            value: /manifest.json
      filters:
        - type: ExtensionRef
          extensionRef:
            group: traefik.io
            kind: Middleware
            name: http-cache
      backendRefs:
        - name: mealie-service
          port: 9000

    # Rule 2: Dynamic API & Application Root (UNCACHED / COMPRESSED)
    - matches:
        - path:
            type: PathPrefix
            value: /
      filters:
        - type: ExtensionRef
          extensionRef:
            group: traefik.io
            kind: Middleware
            name: compress
      backendRefs:
        - name: mealie-service
          port: 9000
