apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home

labels:
  - pairs:
      app.kubernetes.io/name: mealie

# List of resources to include
resources:
  - db-external-secret.yaml
  - secrets.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - http-route.yaml
  - network-policy.yaml

images:
  - name: ghcr.io/mealie-recipes/mealie
    newTag: v3.18.0@sha256:2db8344499efc5a7b2efcf079f140a2931cc325361f65a44e6a5bd1a0607b610
