apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home

labels:
  - pairs:
      app.kubernetes.io/name: mealie

# List of resources to include
resources:
  - db-external-secret.yaml
  - secrets.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - http-route.yaml
  - network-policy.yaml

images:
  - name: ghcr.io/mealie-recipes/mealie
    newTag: v3.16.0@sha256:74496aed2c5055e3b7b6c4e1bb9b4f16b1f566601582b258a10bae851f19ac24
