apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home

labels:
  - pairs:
      app.kubernetes.io/name: mealie

# List of resources to include
resources:
  - db-external-secret.yaml
  - secrets.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - http-route.yaml
  - network-policy.yaml

images:
  - name: ghcr.io/mealie-recipes/mealie
    newTag: v3.24.0@sha256:0b08ac3a9f0a65b8298bcb3a9fcb596f870f92fbefbecd8fffe075fa9b6d2d5d
