apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: iot

labels:
  - pairs:
      app.kubernetes.io/name: otbr-agent

resources:
  - deployment.yaml
  - service.yaml
  - persistence

configMapGenerator:
  - name: otbr-proxy
    files:
      - proxy.go


