apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: otbr-policy
spec:
  endpointSelector:
    matchLabels:
      app: otbr-agent

  # ----=== Ingress ===----
  ingress:
    # Allow mDNS, Thread discovery & Multicast Ingress
    - fromCIDR:
        - 192.168.4.0/24
        - fd00::/8
        - fc00::/7
        - fe80::/10
        - 224.0.0.0/4
        - ff00::/8

    # Allow Ingress from Home Assistant
    - fromEndpoints:
        - matchLabels:
            app: home-assistant
            k8s:io.kubernetes.pod.namespace: iot
      toPorts:
        - ports:
            - port: "80"
              protocol: TCP
            - port: "8081"
              protocol: TCP

  # ----=== Egress ===----
  egress:
    # Egress to Serial-over-IP Coordinator (SLZB-06M)
    - toCIDR:
        - 192.168.4.46/32
      toPorts:
        - ports:
            - port: "6638"
              protocol: TCP

    # Egress to IoT VLAN, HomeLab VLAN, Thread Subnets & Multicast
    - toCIDR:
        - 192.168.4.0/24
        - 10.10.1.0/24
        - fd00::/8
        - fc00::/7
        - fe80::/10
        - 224.0.0.0/4
        - ff00::/8

    # Egress to Internet (World)
    - toEntities:
        - "world"
      toPorts:
        - ports:
            - port: "80"
              protocol: TCP
            - port: "443"
              protocol: TCP
            - port: "123"
              protocol: UDP
