apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: otbr-credentials-es
spec:
  target:
    name: otbr-credentials
    creationPolicy: Owner

  secretStoreRef:
    name: vaultwarden-fields
    kind: ClusterSecretStore

  data:
    - secretKey: dataset
      remoteRef:
        key: "80070fe9-e88c-49f6-b2aa-e4af1f0cb89b"
        property: "THREAD_DATASET"
