apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: otbr-credentials-es
spec:
  target:
    name: otbr-credentials
    creationPolicy: Owner

  secretStoreRef:
    name: openbao-store
    kind: ClusterSecretStore

  data:
    - secretKey: dataset
      remoteRef:
        key: iot/otbr
        property: dataset
