apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: networking

helmCharts:
  - name: keda
    repo: https://kedacore.github.io/charts
    version: 2.20.1
    releaseName: keda
    namespace: networking
  - name: keda-add-ons-http
    repo: https://kedacore.github.io/charts
    version: 0.15.0
    releaseName: keda-add-ons-http
    namespace: networking
    valuesInline:
      operator:
        resources:
          requests:
            cpu: 20m
            memory: 32Mi
          limits:
            cpu: 100m
            memory: 128Mi
      scaler:
        resources:
          requests:
            cpu: 20m
            memory: 32Mi
          limits:
            cpu: 100m
            memory: 128Mi
      interceptor:
        resources:
          requests:
            cpu: 20m
            memory: 32Mi
          limits:
            cpu: 100m
            memory: 128Mi


resources:
  - namespace.yaml
  - network-policy.yaml
  - reference-grant.yaml

patches:
  - patch: |-
      apiVersion: v1
      kind: Service
      metadata:
        name: keda-add-ons-http-interceptor-proxy
      spec:
        ipFamilyPolicy: PreferDualStack
        ipFamilies:
        - IPv4
        - IPv6
    target:
      kind: Service
      name: keda-add-ons-http-interceptor-proxy
