apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: daily-s3-backup
  namespace: longhorn-system
spec:
  cron: "0 2 * * *" # Runs daily at 2 AM
  task: "backup"
  retain: 3
  concurrency: 1
  labels:
    type: "daily"
