apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: s3-backup-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-store
  target:
    creationPolicy: Owner
    name: s3-backup-secret
    template:
      type: Opaque
      data:
        WEED_JWT_FILER_SIGNING_KEY: "{{ .WEED_JWT_FILER_SIGNING_KEY }}"
        WEED_S3_SSE_KEK_PASSPHRASE: "{{ .WEED_S3_SSE_KEK_PASSPHRASE }}"
        AWS_ACCESS_KEY_ID: "{{ .AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .AWS_SECRET_ACCESS_KEY }}"
        AWS_ENDPOINTS: "https://s3.kerrlab.app"
  data:
    - remoteRef:
        key: platform/s3/backup-filers
        property: WEED_JWT_FILER_SIGNING_KEY
      secretKey: WEED_JWT_FILER_SIGNING_KEY
    - remoteRef:
        key: platform/s3/backup-filers
        property: WEED_S3_SSE_KEK_PASSPHRASE
      secretKey: WEED_S3_SSE_KEK_PASSPHRASE
    - remoteRef:
        key: platform/s3/backup-filers
        property: AWS_ACCESS_KEY_ID
      secretKey: AWS_ACCESS_KEY_ID
    - remoteRef:
        key: platform/s3/backup-filers
        property: AWS_SECRET_ACCESS_KEY
      secretKey: AWS_SECRET_ACCESS_KEY
