apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: s3-backup-secret
spec:
  refreshInterval: 1h
  target:
    creationPolicy: Owner
    name: s3-backup-secret
    template:
      type: Opaque
      data:
        WEED_JWT_FILER_SIGNING_KEY: "{{ .WEED_JWT_FILER_SIGNING_KEY }}"
        WEED_S3_SSE_KEK_PASSPHRASE: "{{ .WEED_S3_SSE_KEK_PASSPHRASE }}"
        AWS_ACCESS_KEY_ID: "{{ .AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .AWS_SECRET_ACCESS_KEY }}"
        AWS_ENDPOINTS: "https://s3.kerrlab.app"
  data:
    - remoteRef:
        key: bb7d5c3e-2ff7-4a42-a63b-0f86e5337b81
        property: WEED_JWT_FILER_SIGNING_KEY
      secretKey: WEED_JWT_FILER_SIGNING_KEY
      sourceRef:
        storeRef:
          name: vaultwarden-fields
          kind: ClusterSecretStore
    - remoteRef:
        key: bb7d5c3e-2ff7-4a42-a63b-0f86e5337b81
        property: WEED_S3_SSE_KEK_PASSPHRASE
      secretKey: WEED_S3_SSE_KEK_PASSPHRASE
      sourceRef:
        storeRef:
          name: vaultwarden-fields
          kind: ClusterSecretStore
    - remoteRef:
        key: bb7d5c3e-2ff7-4a42-a63b-0f86e5337b81
        property: AWS_ACCESS_KEY_ID
      secretKey: AWS_ACCESS_KEY_ID
      sourceRef:
        storeRef:
          name: vaultwarden-fields
          kind: ClusterSecretStore
    - remoteRef:
        key: bb7d5c3e-2ff7-4a42-a63b-0f86e5337b81
        property: AWS_SECRET_ACCESS_KEY
      secretKey: AWS_SECRET_ACCESS_KEY
      sourceRef:
        storeRef:
          name: vaultwarden-fields
          kind: ClusterSecretStore
