apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-store
  target:
    name: cloudflare-api-token-secret
    creationPolicy: Owner
  data:
    - secretKey: api-token
      remoteRef:
        key: platform/cloudflare
        property: api-token