apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zero-ssl-eabsecret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-store
  target:
    name: zero-ssl-eabsecret
    creationPolicy: Owner
  data:
    - secretKey: kid
      remoteRef:
        key: platform/zerossl
        property: kid
    - secretKey: secret
      remoteRef:
        key: platform/zerossl
        property: secret