apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: unpackerr-app-secrets
spec:
  target:
    name: unpackerr-app-secrets

  secretStoreRef:
    name: openbao-store
    kind: ClusterSecretStore

  data:
    # ---- Radarr ----
    - secretKey: radarr_key
      remoteRef:
        key: media/unpackerr
        property: radarr_key
    # ---- Sonarr ----
    - secretKey: sonarr_tv_key
      remoteRef:
        key: media/unpackerr
        property: sonarr_tv_key
    - secretKey: sonarr_anime_key
      remoteRef:
        key: media/unpackerr
        property: sonarr_anime_key
