apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: seerr
  name: seerr-config-longhorn-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn
  volumeMode: Filesystem
