# authelia/daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: authelia
  labels:
    app: authelia
spec:
  selector:
    matchLabels:
      app: authelia
  template:
    metadata:
      labels:
        app: authelia
        networking/expose-web-ui: "true"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10000
        runAsGroup: 10000
        fsGroup: 10000
      enableServiceLinks: false
      initContainers:
        - name: prepare-config
          image: ghcr.io/hononeko/k8s-config-tools
          command:
            - gomplate
            - -f
            - /config_templates/configuration-template.yml
            - -o
            - /config/configuration.yml
          envFrom: # This injects all keys from the secret as environment variables
            - secretRef:
                name: authelia-secrets
            - secretRef:
                name: authelia-oidc-secrets
          volumeMounts:
            - name: config-template-volume
              mountPath: /config_templates
            - name: config-volume
              mountPath: /config
            - name: authelia-keys
              mountPath: /config/secrets
          securityContext:
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 50m
              memory: 64Mi
      containers:
        - name: authelia
          image: ghcr.io/authelia/authelia
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          ports:
            - name: web-ui
              containerPort: 9091
              protocol: TCP
          env:
            - name: X_AUTHELIA_CONFIG_FILTERS
              value: "template"
          # Load all keys from the 'authelia-secrets' Secret as environment variables
          envFrom:
            - secretRef:
                name: authelia-secrets
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 1000m
              memory: 256Mi
          volumeMounts:
            - name: config-volume
              mountPath: /config
            - name: authelia-keys
              mountPath: /config/secrets

      volumes:
        - name: authelia-keys
          secret:
            secretName: authelia-secrets-files
            items:
              - key: oidc_private.pem
                path: oidc/jwks/oidc_private.pem
        - name: config-template-volume
          configMap:
            name: authelia-config
        - name: config-volume
          emptyDir: {}
