apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: security
resources:
  - namespace.yaml
  - secrets.yaml
  - oidc-secrets.yaml
  - daemonset.yaml
  - http-route.yaml
  - rate-limit.yaml
  - service.yaml
  - network-policy.yaml
  - dragonfly.yaml
  - dragonfly-network-policy.yaml
images:
  - name: ghcr.io/hononeko/k8s-config-tools
    newTag: 0.1.1@sha256:fb03e8e7910a51472309b361675f38da44ee398ab6ec64b020b660d4d0d4e400
  - name: ghcr.io/authelia/authelia
    newTag: 4.39.22@sha256:936134132eaf01bfa2faf85055afbc1e0cc1cc5ca4547e9c06408fd0dd784646
  - name: ghcr.io/dragonflydb/dragonfly
    newTag: v1.40.1@sha256:ebf3c6c213e82fb51b4521660cca13f06f3421dc5b1ed14f2f474c50b5e29986
configMapGenerator:
  - name: authelia-config
    files:
      - configuration-template.yml=templates/configuration.yaml
