apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: security
resources:
  - namespace.yaml
  - secrets.yaml
  - oidc-secrets.yaml
  - daemonset.yaml
  - http-route.yaml
  - rate-limit.yaml
  - service.yaml
  - network-policy.yaml
  - dragonfly.yaml
  - dragonfly-network-policy.yaml
images:
  - name: ghcr.io/hononeko/k8s-config-tools
    newTag: 0.1.1@sha256:fb03e8e7910a51472309b361675f38da44ee398ab6ec64b020b660d4d0d4e400
  - name: ghcr.io/authelia/authelia
    newTag: 4.39.21@sha256:b2a221b30da111d6717bdf81bdf0b180915921447dde4c533a796c9a33a75d72
  - name: ghcr.io/dragonflydb/dragonfly
    newTag: v1.40.2@sha256:18afa43e911f1dff18c7d1eb452361876d9702bb1cdff5c5d75c69617a4065c9
configMapGenerator:
  - name: authelia-config
    files:
      - configuration-template.yml=templates/configuration.yaml
