apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: security
resources:
  - namespace.yaml
  - secrets.yaml
  - oidc-secrets.yaml
  - config.yaml
  - daemonset.yaml
  - http-route.yaml
  - service.yaml
  - network-policy.yaml
  - redis-cluster.yaml
  - redis-network-policy.yaml
images:
  - name: alpine/k8s
    newTag: 1.35.2@sha256:9a87b09e1b6d887fa52c2dea1611d112d9e7d3d0271708588711a2fb2016e82c
  - name: ghcr.io/authelia/authelia
    newTag: 4.39.16@sha256:edbce01c5125249e4f4faea01e0f76f0031d64b4a1d0c2514a0ca69cb126d05f
