# authelia/external-secret.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authelia-oidc-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-store

  target:
    name: authelia-oidc-secrets
    creationPolicy: Owner

  data:
      # ---- Bar Assistant ----
    - secretKey: BAR_ASSISTANT_SECRET
      remoteRef:
        key: security/authelia/oidc-clients
        property: BAR_ASSISTANT_SECRET
      # ---- Mealie ----
    - secretKey: MEALIE_SECRET
      remoteRef:
        key: security/authelia/oidc-clients
        property: MEALIE_SECRET
      # ---- Autobrr ----
    - secretKey: AUTOBRR_SECRET
      remoteRef:
        key: security/authelia/oidc-clients
        property: AUTOBRR_SECRET
      # ---- Headlamp ----
    - secretKey: HEADLAMP_SECRET
      remoteRef:
        key: security/authelia/oidc-clients
        property: HEADLAMP_SECRET
      # ---- RomM ----
    - secretKey: ROMM_SECRET
      remoteRef:
        key: security/authelia/oidc-clients
        property: ROMM_SECRET
      # ---- NodeCast ----
    - secretKey: NODECAST_SECRET
      remoteRef:
        key: security/authelia/oidc-clients
        property: NODECAST_SECRET
      # ---- Fluxer ----
    - secretKey: FLUXER_SECRET
      remoteRef:
        key: security/authelia/oidc-clients
        property: FLUXER_SECRET
      # ---- OpenBao ----
    - secretKey: OPENBAO_SECRET
      remoteRef:
        key: security/authelia/oidc-clients
        property: OPENBAO_SECRET
      # ---- Kaneo ----
    - secretKey: KANEO_SECRET
      remoteRef:
        key: security/authelia/oidc-clients
        property: KANEO_SECRET
