# authelia/external-secret.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authelia-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-store

  target:
    name: authelia-secrets
    creationPolicy: Owner

  data:
    # ---- JWT ----
    - secretKey: JWT_SECRET
      remoteRef:
        key: security/authelia
        property: JWT_SECRET
    # ---- Session ----
    - secretKey: SESSION_SECRET
      remoteRef:
        key: security/authelia
        property: SESSION_ENCRYPTION_KEY
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: security/authelia
        property: REDIS_PASSWORD
    # ---- LDAP ----
    - secretKey: LDAP_PASSWORD
      remoteRef:
        key: security/authelia
        property: LDAP_PASSWORD
    - secretKey: LDAP_BASE_DN
      remoteRef:
        key: security/authelia
        property: LDAP_BASE_DN
    - secretKey: LDAP_BIND_DN
      remoteRef:
        key: security/authelia
        property: LDAP_BIND_DN
    # ---- Storage ----
    - secretKey: STORAGE_PASSWORD
      remoteRef:
        key: security/authelia
        property: STORAGE_PASSWORD
    - secretKey: STORAGE_ENCRYPTION_KEY
      remoteRef:
        key: security/authelia
        property: STORAGE_ENCRYPTION_KEY
    - secretKey: OIDC_HMAC_SECRET
      remoteRef:
        key: security/authelia
        property: OIDC_HMAC_SECRET
    # ---- Notifier ----
    - secretKey: SMTP_USERNAME
      remoteRef:
        key: security/authelia
        property: SMTP_username
    - secretKey: SMTP_PASSWORD
      remoteRef:
        key: security/authelia
        property: SMTP_token
---
## authelia/external-secret.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authelia-secrets-files
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-store

  target:
    name: authelia-secrets-files
    creationPolicy: Owner

  data:
    # ---- JWT ----
    - secretKey: oidc_private.pem
      remoteRef:
        key: security/authelia
        property: oidc_private.pem