# authelia/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: authelia
  namespace: security
  labels:
    app: authelia
spec:
  type: LoadBalancer
  ports:
    - port: 9091
      targetPort: web-ui
      protocol: TCP
      name: web-ui
  externalTrafficPolicy: Local
  trafficDistribution: PreferSameNode # 1.35 feature
  selector:
    app: authelia
