# values.yaml for strimzi-kafka-operator chart

watchNamespaces:
  - automation

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "250m"
    memory: "256Mi"

# Standard leader election for the operator itself
leaderElection:
  enabled: true