apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - master-key.yaml
  - configmap.yaml
  - service-account.yaml
  - statefulset.yaml
  - service.yaml
  - http-route.yaml
  - network-policy.yaml
images:
  - name: getmeili/meilisearch
    newTag: v1.37.0@sha256:9cde2774864e6c19cdd09fcd2950bc01ac9a0454b6f343fffafa14faae6eb7ea
