apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - master-key.yaml
  - configmap.yaml
  - service-account.yaml
  - statefulset.yaml
  - service.yaml
  - http-route.yaml
  - network-policy.yaml
images:
  - name: getmeili/meilisearch
    newTag: v1.38.0@sha256:5a598ce9cec7b33db09a6a60b55d735e97e7b5632c35c9ad1a2e8fb9e3796654
