apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - network-policy.yaml
  - service.yaml
  - statefulset.yaml
  - storage.yaml

images:
  - name: wolveix/satisfactory-server
    newTag: v1.9.10@sha256:e103700ae6ae4c50f19dac80eadb2a805c5b885e179ae2a40850e967bf189efd
  - name: alpine
    newTag: 3.24.0@sha256:a2d49ea686c2adfe3c992e47dc3b5e7fa6e6b5055609400dc2acaeb241c829f4
