apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - http-route.yaml
  - network-policy.yaml

labels:
  - pairs:
      app.kubernetes.io/name: autobrr
      app.kubernetes.io/part-of: media-services
images:
  - name: ghcr.io/autobrr/autobrr
    newTag: v1.77.0@sha256:7274b735b23ff4d048e7706145ce5759020e4ee6d85bb1fb8cca523784d35f88
