# autobrr/external-secret.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: autobrr-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-store

  target:
    name: autobrr-secret
    creationPolicy: Owner

  data:
    - secretKey: AUTOBRR__OIDC_CLIENT_SECRET
      remoteRef:
        key: media/autobrr
        property: AUTOBRR__OIDC_CLIENT_SECRET
    - secretKey: AUTOBRR__POSTGRES_USER
      remoteRef:
        key: media/autobrr
        property: AUTOBRR__POSTGRES_USER
    - secretKey: AUTOBRR__POSTGRES_PASS
      remoteRef:
        key: media/autobrr
        property: AUTOBRR__POSTGRES_PASS
    - secretKey: AUTOBRR__POSTGRES_HOST
      remoteRef:
        key: media/autobrr
        property: AUTOBRR__POSTGRES_HOST
    - secretKey: AUTOBRR__POSTGRES_PORT
      remoteRef:
        key: media/autobrr
        property: AUTOBRR__POSTGRES_PORT
    - secretKey: AUTOBRR__SESSION_SECRET
      remoteRef:
        key: media/autobrr
        property: AUTOBRR__SESSION_SECRET
