# autobrr/external-secret.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: autobrr-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vaultwarden-fields

  target:
    name: autobrr-secret
    creationPolicy: Owner

  data:
    - secretKey: AUTOBRR__OIDC_CLIENT_SECRET
      remoteRef:
        key: 109f6530-b52d-4005-8531-2b60c16cec8f
        property: OIDC_CLIENT_SECRET
    - secretKey: AUTOBRR__POSTGRES_USER
      remoteRef:
        key: 109f6530-b52d-4005-8531-2b60c16cec8f
        property: postgres_user
    - secretKey: AUTOBRR__POSTGRES_PASS
      remoteRef:
        key: 109f6530-b52d-4005-8531-2b60c16cec8f
        property: postgres_password
    - secretKey: AUTOBRR__POSTGRES_HOST
      remoteRef:
        key: 109f6530-b52d-4005-8531-2b60c16cec8f
        property: postgres_host
    - secretKey: AUTOBRR__POSTGRES_PORT
      remoteRef:
        key: 109f6530-b52d-4005-8531-2b60c16cec8f
        property: postgres_port
    - secretKey: AUTOBRR__SESSION_SECRET
      remoteRef:
        key: 109f6530-b52d-4005-8531-2b60c16cec8f
        property: session_secret
