apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: automation

resources:
  - deployment.yaml
  - service.yaml
  - secret.yaml
  - network-policy.yaml
  - dragonfly.yaml
  - dragonfly-network-policy.yaml

images:
  - name: ghcr.io/hononeko/media-webhook-notifier
    newTag: 2.9.3@sha256:4d7a7e3a010453978737a5aa689b36bdcdbd6b52fa3821cb3a6fc6d672b97918
  - name: ghcr.io/dragonflydb/dragonfly
    newTag: v2.0.0@sha256:7426fdb31ddcf7bd9499b4205f36ebaa83b26149ba1609a0d5f8f474b3631233
