apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: automation

resources:
  - deployment.yaml
  - service.yaml
  - secret.yaml
  - network-policy.yaml

images:
  - name: ghcr.io/hononeko/media-webhook-notifier
    newTag: 2.8.2@sha256:06a15ea1441e6724d867a45ee83645e449d0e735b84a4e4570214dd9da6002e2
