apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: media-webhook-notifier-secret
spec:
  secretStoreRef:
    name: vaultwarden-fields
    kind: ClusterSecretStore
  target:
    name: media-webhook-notifier-secret
  data:
    - secretKey: SERVER_AUTH_TOKEN
      remoteRef:
        key: "00000000-0000-0000-0000-000000000000"
        property: "auth_token"
    - secretKey: TELEGRAM_BOT_TOKEN
      remoteRef:
        key: "00000000-0000-0000-0000-000000000000"
        property: "bot_token"
    - secretKey: TELEGRAM_CHAT_ID
      remoteRef:
        key: "00000000-0000-0000-0000-000000000000"
        property: "chat_id"
    - secretKey: TELEGRAM_TOPIC_ID
      remoteRef:
        key: "00000000-0000-0000-0000-000000000000"
        property: "topic_id"
