apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: media-webhook-notifier-secret
spec:
  secretStoreRef:
    name: vaultwarden-fields
    kind: ClusterSecretStore
  target:
    name: media-webhook-notifier-secret
    template:
      data:
        SERVER_AUTH_TOKEN: "{{ .webhook_token }}"
        NOTIFICATION_URL: "telegram://{{ .bot_token }}@{{ .chat_id }}"
  data:
    - secretKey: webhook_token
      remoteRef:
        key: "2ce41f9c-fbbf-4685-a92d-1efe31573e32"
        property: "WEBHOOK_SECRET"
    - secretKey: bot_token
      remoteRef:
        key: "b2b0ba50-a50e-4529-a89e-ae8b1fb3ac10"
        property: "kerrlab_arr_bot"
    - secretKey: chat_id
      remoteRef:
        key: "b2b0ba50-a50e-4529-a89e-ae8b1fb3ac10"
        property: "homelab_media_channel"
