apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - deployment.yaml
  - service.yaml
  - http-route.yaml
  - httpscaledobject.yaml
  - network-policy.yaml
images:
  - name: ghcr.io/mermaid-js/mermaid-live-editor
    newTag: latest@sha256:152d9f0d5ac4bbdae66a79209a1502ab37faa5ae7ee1b94a33d0aabbe2f96ff6
