apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - deployment.yaml
  - service.yaml
  - http-route.yaml
  - httpscaledobject.yaml
  - network-policy.yaml
images:
  - name: ghcr.io/mermaid-js/mermaid-live-editor
    newTag: latest@sha256:f2c439db8f54133f61296c8be5c59b4a8f0683f4ca57cd91491e94f0c67af4c1
