apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - config.yaml
  - secret.yaml
  - deployment.yaml
  - network-policy.yaml

labels:
  - pairs:
      app.kubernetes.io/name: unpackerr
      app.kubernetes.io/part-of: media-services
images:
  - name: ghcr.io/unpackerr/unpackerr
    newTag: 0.15.0@sha256:9f4cb99b78d8fe2d55f79c490a715e14a8a28d9868373dad642ca5adc2ac3e91
