apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - http-route.yaml
  - network-policy.yaml

labels:
  - pairs:
      app.kubernetes.io/name: tautulli
      app.kubernetes.io/part-of: media-services
images:
  - name: ghcr.io/home-operations/tautulli
    newTag: 2.17.0@sha256:b90b30e15d1b6d12fc726fac1ef9778ad92f405ac8f8ccb30a34d7f6673c113d
