apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - http-route.yaml
  - network-policy.yaml

labels:
  - pairs:
      app.kubernetes.io/name: tautulli
      app.kubernetes.io/part-of: media-services
images:
  - name: ghcr.io/home-operations/tautulli
    newTag: 2.18.2@sha256:5d55eb06f2b77eb09001b2f884b0b3a9ed3adf8416c6209c563796e18eaa43a4
