apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: bar-assistant
  name: bar-assistant-config-longhorn-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn-retain
  volumeMode: Filesystem
