apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: media
resources:
  - statefulset.yaml
  - service.yaml
  - http-route.yaml
  - network-policy.yaml
  - ntfy-credentials-secret.yaml
  - vpn-secret.yaml

labels:
  - pairs:
      app.kubernetes.io/name: qbittorrent
      app.kubernetes.io/part-of: media-services
images:
  - name: alpine/k8s
    newTag: 1.35.2@sha256:9a87b09e1b6d887fa52c2dea1611d112d9e7d3d0271708588711a2fb2016e82c
  - name: ghcr.io/home-operations/qbittorrent
    newTag: 5.1.4@sha256:bb82ad6668f8eda1d0fcce6c1341498bfa879155bb1295cd9d314a2c35c07a01
  - name: ghcr.io/hononeko/qbit-ntfy-sidecar
    newTag: 1.0.0@sha256:4f67bb97cf5ecff4cd4b21c6a15fc24984c66b44dd6df782a325c31b4231c2df
  - name: qmcgaw/gluetun
    newTag: v3.41.1@sha256:1a5bf4b4820a879cdf8d93d7ef0d2d963af56670c9ebff8981860b6804ebc8ab
  - name: ghcr.io/hononeko/qbit-gluetun-sync
    newTag: 1.1.0@sha256:e421022ea0f8e2aab60ff266f429b902cda650e707b3285c76b86f80d69d9328
