apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qbit-secrets
  namespace: media
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vaultwarden-fields
    kind: ClusterSecretStore
  target:
    name: qbit-secrets
    creationPolicy: Owner
  data:
    - secretKey: WEBHOOK_SECRET
      remoteRef:
        key: 5b79147c-2173-45ff-84d9-b55e0ae43d03
        property: WEBHOOK_SECRET
