apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minecraft-vh-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao-store
    kind: ClusterSecretStore
  target:
    name: minecraft-vh-secret
    creationPolicy: Owner
  data:
    - secretKey: CF_API_KEY
      remoteRef:
        key: games/minecraft-vault-hunters
        property: CF_API_KEY
    - secretKey: RCON_PASSWORD
      remoteRef:
        key: games/minecraft-vault-hunters
        property: RCON_PASSWORD