apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: games

# 1. Base Logic
resources:
  - ../../base
  - external-secret.yaml
  - service-voice.yaml


# 2. Add Name Suffix
nameSuffix: -vh

configurations:
  - kustomize-config.yaml

labels:
  - includeSelectors: true
    pairs:
      app: minecraft-vh

images:
  - name: ghcr.io/itzg/minecraft-server
    newTag: stable-java17@sha256:6cc2fc4f1ad839a70feebb300202bbc45ad9ddfa863aba95eadf63ab97e4c01d

# 3. Patches
patches:
  # === Override config ===
  - target:
      kind: ConfigMap
      name: minecraft-config
    patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: minecraft-config
      data:
        #  CF_PAGE_URL: "https://www.curseforge.com/minecraft/modpacks/vault-hunters-1-18-2"
        CF_SLUG: "vault-hunters-1-18-2"
        CF_FORCE_SYNCHRONIZE: "TRUE"
        TYPE: "AUTO_CURSEFORGE"
        VERSION: "1.18.2"
        OPS: "Kerrlab,JusApee"
        SERVER_NAME: "Vault Hunters S4 Server"
        DIFFICULTY: "hard"
        SPAWN_PROTECTION: "0"
        USE_AIKAR_FLAGS: "TRUE"
        USE_MEOWICE_FLAGS: "TRUE"
        # USE_MEOWICE_GRAALVM_FLAGS: "TRUE"
        INIT_MEMORY: "4G"
        MAX_MEMORY: "6G"
        VIEW_DISTANCE: "16"
        MODE: "survival"
        WHITELIST: "Kerrlab,JusApee"
        OVERRIDE_WHITELIST: "true"
        CF_FORCE_INCLUDE_MODS: "spark"
        CF_OVERRIDES_SKIP_EXISTING: "true"
        ENABLE_AUTOPAUSE: "TRUE"
        AUTOPAUSE_TIMEOUT_ESTABLISHED: "900"
        AUTOPAUSE_TIMEOUT_INIT: "600"
        VOICE_CHAT_PORT: "24455"

  # === Override backup schedule ===
  - target:
      kind: ConfigMap
      name: minecraft-backup-script
    patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: minecraft-backup-script
      data:
        DEFAULT_BACKUP_SCHEDULE: "20 * * * *"

  # === Increase default storage size ===
  - target:
      kind: PersistentVolumeClaim
      name: minecraft-data-pvc
    patch: |-
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: minecraft-data-pvc
      spec:
        resources:
          requests:
            storage: 64Gi # Increased from the base 20Gi

  # === Update backup PV for overlay ===
  - target:
      kind: PersistentVolume
      name: minecraft-backup-nfs
    patch: |-
      apiVersion: v1
      kind: PersistentVolume
      metadata:
        name: minecraft-backup-nfs
        labels:
          pv-name: minecraft-backup-nfs-vh # Add suffix to label
      spec:
        nfs:
          # Using a folder for this instance of minecraft
          path: /volume1/cluster/minecraft/vault-hunters

  # === Patch base PVC so it refers the defined PV and deployment refers to renamed PVC ===
  - target:
      kind: PersistentVolumeClaim
      name: minecraft-backup-pvc
    patch: |-
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: minecraft-backup-pvc # Matches Base Name
      spec:
        selector:
          matchLabels:
            pv-name: minecraft-backup-nfs-vh

  # === Patch Deployment (Aux Mount + Unique Secret) ===
  - target:
      kind: StatefulSet
      name: minecraft
    patch: |-
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: minecraft
      spec:
        template:
          spec:
            containers:
              - name: minecraft
                resources:
                  requests:
                    memory: "6Gi"
                  limits:
                    memory: "8Gi"

                envFrom:
                  - configMapRef:
                      name: minecraft-config
                  - secretRef:
                      name: minecraft-vh-secret
                env:
                  - name: RCON_PASSWORD
                    valueFrom:
                      secretKeyRef:
                        name: minecraft-vh-secret
                        key: RCON_PASSWORD

              - name: backup-sidecar
                env:
                  - name: RCON_PASSWORD
                    valueFrom:
                      secretKeyRef:
                        name: minecraft-vh-secret
                        key: RCON_PASSWORD

  # === Patch Service (Internal ClusterIP for mc-router routing) ===
  - target:
      kind: Service
      name: minecraft
    patch: |-
      apiVersion: v1
      kind: Service
      metadata:
        name: minecraft
        annotations:
          mc-router.itzg.me/externalServerName: "mc-vh.kerrlab.app,vh.mc.kerrlab.app"
      spec:
        $patch: replace
        type: ClusterIP
        selector:
          app: minecraft-vh
        ports:
          - name: minecraft-tcp
            port: 25565
            targetPort: 25565
            protocol: TCP
          - name: voice-udp
            port: 24455
            targetPort: 24454
            protocol: UDP

