persistence:
  defaultClassReplicaCount: 2
ingress:
  enabled: false

defaultSettings:
  # Do not automatically create disks on all nodes. 
  # This allows us to control which nodes provide storage via labels.
  createDefaultDiskLabeledNodes: true
  # Ensure control planes aren't used by default unless necessary.
  # We will keep this false for now because we need lab-2 and lab-3.
  disableSchedulingOnControlPlane: false
  # Set to 15% for smaller disks
  storageMinimalAvailablePercentage: 15
  # Limit CPU impact on N100s during rebuilding
  concurrentReplicaRebuildPerNodeLimit: 1
  # Default Backup Target
  backupTarget: "s3://longhorn-backups@us-east-1/"
  backupTargetCredentialSecret: "s3-backup-secret"

longhornManager:
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "1000m"
      memory: "1Gi"

longhornDriverDeployer:
  resources:
    requests:
      cpu: "10m"
      memory: "64Mi"
    limits:
      cpu: "100m"
      memory: "128Mi"

longhornUI:
  resources:
    requests:
      cpu: "10m"
      memory: "64Mi"
    limits:
      cpu: "100m"
      memory: "128Mi"


