---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: penpot-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao-store
    kind: ClusterSecretStore
  target:
    name: penpot-secrets
    creationPolicy: Owner
  data:
    - secretKey: PENPOT_SECRET_KEY
      remoteRef:
        key: tools/penpot
        property: PENPOT_SECRET
    - secretKey: POSTGRES_USER
      remoteRef:
        key: tools/penpot
        property: POSTGRES_USER
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: tools/penpot
        property: POSTGRES_PASSWORD
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        key: security/authelia/oidc-clients
        property: PENPOT_SECRET
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: platform/s3/backup-filers
        property: AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: platform/s3/backup-filers
        property: AWS_SECRET_ACCESS_KEY
