---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tools

helmCharts:
  - name: penpot
    repo: https://helm.penpot.app
    version: 1.11.2
    releaseName: penpot
    namespace: tools
    valuesFile: values/values.yml

resources:
  - frontend-mcp-config.yaml
  - external-secrets.yaml
  - valkey.yaml
  - http-route.yaml
  - network-policy.yaml

patches:
  - target:
      kind: Deployment
      name: penpot-frontend
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/ports/0/name
        value: web-ui
      - op: add
        path: /spec/template/spec/volumes/-
        value:
          name: mcp-messages-config
          configMap:
            name: penpot-frontend-mcp-config
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/-
        value:
          name: mcp-messages-config
          mountPath: /etc/nginx/overrides/server.d/mcp-messages.conf
          subPath: mcp-messages.conf
  - target:
      kind: Service
      name: penpot
    patch: |-
      - op: replace
        path: /spec/ports/0/name
        value: web-ui
  - patch: |-
      $patch: delete
      apiVersion: v1
      kind: Pod
      metadata:
        name: penpot-test-connection
        namespace: tools
