apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tools

helmCharts:
  - name: penpot
    repo: http://helm.penpot.app
    version: 1.10.0
    releaseName: penpot
    namespace: tools
    valuesFile: values/values.yml

resources:
  - external-secrets.yaml
  - valkey.yaml
  - http-route.yaml
  - network-policy.yaml

patches:
  - target:
      kind: Deployment
      name: penpot-frontend
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/ports/0/name
        value: web-ui
  - target:
      kind: Service
      name: penpot
    patch: |-
      - op: replace
        path: /spec/ports/0/name
        value: web-ui
  - patch: |-
      $patch: delete
      apiVersion: v1
      kind: Pod
      metadata:
        name: penpot-test-connection
        namespace: tools
