apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: security
resources:
  - config.yaml
  - secrets.yaml
  - deployment.yaml
  - http-route.yaml
  - middlewares.yaml
  - service.yaml
  - network-policy.yaml
  - dragonfly.yaml
  - dragonfly-network-policy.yaml
images:
  - name: quay.io/oauth2-proxy/oauth2-proxy
    newTag: v7.15.4@sha256:b1b2021fe8f4004573e8d690dec6c7bb29cc44364572cf8510a05bf3a0ae2ded
  - name: ghcr.io/dragonflydb/dragonfly
    newTag: v1.40.1@sha256:ebf3c6c213e82fb51b4521660cca13f06f3421dc5b1ed14f2f474c50b5e29986
