apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: security
resources:
  - config.yaml
  - secrets.yaml
  - deployment.yaml
  - http-route.yaml
  - middlewares.yaml
  - service.yaml
  - network-policy.yaml
  - dragonfly.yaml
  - dragonfly-network-policy.yaml
images:
  - name: quay.io/oauth2-proxy/oauth2-proxy
    newTag: v7.15.4@sha256:b1b2021fe8f4004573e8d690dec6c7bb29cc44364572cf8510a05bf3a0ae2ded
  - name: ghcr.io/dragonflydb/dragonfly
    newTag: v1.40.2@sha256:18afa43e911f1dff18c7d1eb452361876d9702bb1cdff5c5d75c69617a4065c9
