apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: security
resources:
  - config.yaml
  - secrets.yaml
  - deployment.yaml
  - http-route.yaml
  - middlewares.yaml
  - service.yaml
  - network-policy.yaml
  - redis-cluster.yaml
  - redis-network-policy.yaml
images:
  - name: quay.io/oauth2-proxy/oauth2-proxy
    newTag: v7.15.3@sha256:10a1165743a192e1940b4708fb9647027185ce11a681a1c5519b442ff7f1f561
