apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: nodecast-tv
spec:
  hosts:
    - nodecast.kerrlab.app
  scaleTargetRef:
    name: nodecast-tv
    kind: Deployment
    apiVersion: apps/v1
    service: nodecast-tv
    port: 3000
  replicas:
    min: 0
    max: 1
  scaledownPeriod: 600
