apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: nodecast-tv-policy
spec:
  endpointSelector:
    matchLabels:
      app: nodecast-tv


  # ----=== Egress ===----
  egress:
    # === Allow access to external ===
    - toEntities:
        - "world"
    # === Allow access to Traefik (for OIDC) ===
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: traefik
            app.kubernetes.io/name: traefik
      toPorts:
        - ports:
            - port: "443"
              protocol: "TCP"
            - port: "80"
              protocol: "TCP"
