apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: nodecast-tv-policy
spec:
  endpointSelector:
    matchLabels:
      app: nodecast-tv

  # ----=== Ingress ===----
  ingress:
    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: networking
            app.kubernetes.io/component: interceptor
      toPorts:
        - ports:
            - port: "3000"
              protocol: "TCP"

  # ----=== Egress ===----
  egress:
    # === Allow access to external and host network ===
    - toEntities:
        - "world"
        - "host"
        - "remote-node"
    # === Allow access to local reverse proxy (10.10.1.16) for loopback HTTP/HTTPS resolution ===
    - toCIDR:
        - "10.10.1.16/32"
      toPorts:
        - ports:
            - port: "443"
              protocol: "TCP"
            - port: "80"
              protocol: "TCP"
    # === Allow access to Traefik (for OIDC) ===
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: traefik
            app.kubernetes.io/name: traefik
      toPorts:
        - ports:
            - port: "443"
              protocol: "TCP"
            - port: "80"
              protocol: "TCP"
            - port: "9443"
              protocol: "TCP"
            - port: "8443"
              protocol: "TCP"
    - toServices:
        - k8sService:
            serviceName: traefik-internal
            namespace: traefik
