apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nodecast-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao-store
    kind: ClusterSecretStore
  target:
    name: nodecast-secrets
    creationPolicy: Owner
  data:
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        key: media/nodecast
        property: OIDC_CLIENT_SECRET
