apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: data-services
resources:
  - master-key.yaml
  - configmap.yaml
  - service-account.yaml
  - statefulset.yaml
  - service.yaml
  - http-route.yaml
  - external-http-route.yaml
  - rate-limit.yaml
  - network-policy.yaml
images:
  - name: getmeili/meilisearch
    newTag: v1.47.0@sha256:4931c0afd68b12d3db4a608268c6785bba26d3f3b43a228eff62ec38d5a47d8d
