apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: data-services
resources:
  - master-key.yaml
  - configmap.yaml
  - service-account.yaml
  - statefulset.yaml
  - service.yaml
  - http-route.yaml
  - external-http-route.yaml
  - rate-limit.yaml
  - network-policy.yaml
images:
  - name: getmeili/meilisearch
    newTag: v1.48.1@sha256:ad98ec0ab2a387da5c140fe9d935eadc6e3a42aee185b4249dfafd985fb49e1c
