apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: data-services
resources:
  - master-key.yaml
  - configmap.yaml
  - service-account.yaml
  - statefulset.yaml
  - service.yaml
  - http-route.yaml
  - external-http-route.yaml
  - rate-limit.yaml
  - network-policy.yaml
images:
  - name: getmeili/meilisearch
    newTag: v1.49.0@sha256:bdc7d7e7939911c40d88d6bcd01f9c72c81f7293135916d48bce241569f721bd
