apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: meilisearch-kubernetes-master-key
spec:
  target:
    name: meilisearch-kubernetes-master-key

  secretStoreRef:
    name: openbao-store
    kind: ClusterSecretStore

  data:
    - secretKey: MEILI_MASTER_KEY
      remoteRef:
        key: data-services/meilisearch
        property: MEILI_MASTER_KEY