apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: meilisearch-policy
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: meilisearch
  # ----=== Ingress ===----
  ingress:
    # === Allow access from Bar Assistant ===
    - fromEndpoints:
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": home
            "app": bar-assistant
      toPorts:
        - ports:
            - port: "7700"
              protocol: TCP
    # === Allow access from Fluxer API and Worker ===
    - fromEndpoints:
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": comms
            "app": api
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": comms
            "app": worker
      toPorts:
        - ports:
            - port: "7700"
              protocol: TCP
    # === Allow access from Traefik (external route) ===
    - fromEndpoints:
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": traefik
      toPorts:
        - ports:
            - port: "7700"
              protocol: TCP
