apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: meilisearch-policy
  namespace: default
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: meilisearch
  # ----=== Ingress ===----
  ingress:
    # === Allow access from Bar Assistant ===
    - fromEndpoints:
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": home
            "app": bar-assistant
      toPorts:
        - ports:
            - port: "7700"
              protocol: TCP
