apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: workloads-games-auto
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: romm
            path: apps/workloads/games/romm
          - name: mc-router
            path: apps/workloads/games/mc-router
  template:
    metadata:
      name: "{{name}}"
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/vehkiya/homelab-k8s.git
        targetRevision: HEAD
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "games"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
  syncPolicy:
    preserveResourcesOnDeletion: true
