apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: workloads-games
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: romm
            path: apps/workloads/games/romm
          - name: minecraft-vanilla
            path: apps/workloads/games/minecraft/overlays/vanilla
          - name: minecraft-vault-hunters
            path: apps/workloads/games/minecraft/overlays/vault-hunters
  template:
    metadata:
      name: '{{name}}'
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: https://github.com/vehkiya/homelab-k8s.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: 'games'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
  syncPolicy:
    preserveResourcesOnDeletion: true
