apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: uptime-kuma-policy
  namespace: observability
spec:
  endpointSelector:
    matchLabels:
      app: uptime-kuma

  # ----=== Egress ===----
  egress:
    # === Allow access to ntfy ===
    - toServices:
        - k8sService:
            serviceName: ntfy
            namespace: automation
    # === Allow Internet Access for monitoring ===
    - toEntities:
        - "world"
      toPorts:
        - ports:
            - port: "80"
              protocol: TCP
            - port: "443"
              protocol: TCP
            - port: "443"
              protocol: UDP
    - toCIDR:
        - 10.10.1.16/32
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
            - port: "443"
              protocol: UDP
