apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: romm
spec:
  hosts:
    - romm.kerrlab.app
  scaleTargetRef:
    name: romm
    kind: Deployment
    apiVersion: apps/v1
    service: romm-ui
    port: 8080
  replicas:
    min: 0
    max: 1
  cooldownPeriod: 900
