apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - config.yaml
  - secret.yaml
  - service.yaml
  - deployment.yaml
  - http-route.yaml
  - external-http-route.yaml
  - httpscaledobject.yaml
  - rate-limit.yaml
  - http-cache-middleware.yaml
  - network-policy.yaml
images:
  - name: rommapp/romm
    newTag: 5.3.1@sha256:0d66b4ea152a237c7f24b95e87459f46d3c596a7c0b35a82f26bc971487278b3
