apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - config.yaml
  - secret.yaml
  - service.yaml
  - deployment.yaml
  - http-route.yaml
  - external-http-route.yaml
  - httpscaledobject.yaml
  - rate-limit.yaml
  - network-policy.yaml
images:
  - name: rommapp/romm
    newTag: 5.2.0@sha256:3512f2ca455782f90247271bed23116e6bc675bc74e379be2c41696e607ab11e
