apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - config.yaml
  - secret.yaml
  - service.yaml
  - deployment.yaml
  - http-route.yaml
  - external-http-route.yaml
  - httpscaledobject.yaml
  - rate-limit.yaml
  - network-policy.yaml
images:
  - name: rommapp/romm
    newTag: 5.1.0@sha256:ce9d86ab531e09fede45d00f426e3bf2d1f5dd14846f94d6360d77a92a413028
