apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: romm-secret
spec:
  secretStoreRef:
    name: openbao-store
    kind: ClusterSecretStore
  target:
    name: romm-secret
  data:
    # ---- DB ----
    - secretKey: DB_HOST
      remoteRef:
        key: games/romm
        property: DB_HOST
    - secretKey: DB_NAME
      remoteRef:
        key: games/romm
        property: DB_NAME
    - secretKey: DB_USER
      remoteRef:
        key: games/romm
        property: DB_USER
    - secretKey: DB_PASSWD
      remoteRef:
        key: games/romm
        property: DB_PASSWD
    # ---- Auth ----
    - secretKey: ROMM_AUTH_SECRET_KEY
      remoteRef:
        key: games/romm
        property: ROMM_AUTH_SECRET_KEY
    # ---- Screenscraper ----
    - secretKey: SCREENSCRAPER_USER
      remoteRef:
        key: games/romm
        property: SCREENSCRAPER_USER
    - secretKey: SCREENSCRAPER_PASSWORD
      remoteRef:
        key: games/romm
        property: SCREENSCRAPER_PASSWORD
    # ---- RetroAchievements ----
    - secretKey: RETROACHIEVEMENTS_API_KEY
      remoteRef:
        key: games/romm
        property: RETROACHIEVEMENTS_API_KEY
    # ---- SteamGripDB ----
    - secretKey: STEAMGRIDDB_API_KEY
      remoteRef:
        key: games/romm
        property: STEAMGRIDDB_API_KEY
    # ---- IGDB ----
    - secretKey: IGDB_CLIENT_ID
      remoteRef:
        key: games/romm
        property: IGDB_CLIENT_ID
    - secretKey: IGDB_CLIENT_SECRET
      remoteRef:
        key: games/romm
        property: IGDB_CLIENT_SECRET
    # ---- OIDC ----
    - secretKey: OIDC_CLIENT_ID
      remoteRef:
        key: games/romm
        property: OIDC_CLIENT_ID
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        key: games/romm
        property: OIDC_CLIENT_SECRET

#    - secretKey: OIDC_REDIRECT_URI
#      remoteRef:
#        key: "364cbd52-99de-4fe6-ad62-57d23f2fdde5"
#        property: "OIDC_REDIRECT_URI"
#    - secretKey: OIDC_SERVER_APPLICATION_URL
#      remoteRef:
#        key: "364cbd52-99de-4fe6-ad62-57d23f2fdde5"
#        property: "OIDC_SERVER_APPLICATION_URL"
