apiVersion: v1
kind: PersistentVolume
metadata:
  name: mealie-config-pv
  labels:
    pv-name: mealie-config-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4.1
    - async
    - noatime
    - rsize=1048576
    - wsize=1048576
  nfs:
    server: fortress.kerrlab.app
    path: /volume1/cluster/home/mealie
  storageClassName: synostorage-nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie-config-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      pv-name: mealie-config-pv
  storageClassName: synostorage-nfs
