apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    version: 82.12.0
    releaseName: kube-prometheus-stack
    namespace: observability
    valuesFile: values/values.yaml
    includeCRDs: true
resources:
  - secrets.yaml
  - network-policies.yaml
  - http-route.yaml

patches:
  - path: patch-grafana-deployment.yaml
  - path: patch-grafana-service.yaml
