apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-secrets-grafana
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-store
  target:
    name: app-secrets-grafana
    creationPolicy: Owner
    template:
      metadata:
        labels:
          app: grafana
  data:
    - secretKey: user
      remoteRef:
        key: observability/grafana
        property: username
    - secretKey: password
      remoteRef:
        key: observability/grafana
        property: password