apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: it-tools
spec:
  hosts:
    - tools.kerrlab.app
  scaleTargetRef:
    name: it-tools
    kind: Deployment
    apiVersion: apps/v1
    service: it-tools-ui
    port: 80
  replicas:
    min: 0
    max: 1
