apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: games

resources:
  - rbac.yaml
  - service.yaml
  - deployment.yaml
  - network-policy.yaml

configMapGenerator:
  - name: mc-router-config
    files:
      - config.yaml=template/config.yaml

images:
  - name: ghcr.io/itzg/mc-router
    newTag: 1.4.2@sha256:d8b7b75f97ee899c754d924d5506a72e8111956e18f8e0be22a61ddaccd6beaa

