apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - network-policies.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - http-route.yaml

configMapGenerator:
  - name: posterizarr-configmap
    files:
      - config.json.template=templates/config.json
generatorOptions:
  disableNameSuffixHash: true

labels:
  - pairs:
      app.kubernetes.io/name: posterizarr
      app.kubernetes.io/part-of: media-services
images:
  - name: alpine/k8s
    newTag: 1.35.3@sha256:097aa60cbef561146757c7494468e9d7b04d843597ad1a1515ed09d0708c8014
  - name: ghcr.io/fscorrupt/posterizarr
    newTag: 2.2.35@sha256:aec1f3717af57f8644b0b44f2acaee77ef1fc6c3e2c64a412940d2eeeac489af
