apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - network-policies.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - http-route.yaml

configMapGenerator:
  - name: posterizarr-configmap
    files:
      - config.json.template=templates/config.json
generatorOptions:
  disableNameSuffixHash: true

labels:
  - pairs:
      app.kubernetes.io/name: posterizarr
      app.kubernetes.io/part-of: media-services
images:
  - name: ghcr.io/hononeko/k8s-config-tools
    newTag: 0.1.1@sha256:fb03e8e7910a51472309b361675f38da44ee398ab6ec64b020b660d4d0d4e400
  - name: ghcr.io/fscorrupt/posterizarr
    newTag: 3.3.6@sha256:a5dc887ef9171306489bd0c513f3a24fb6b678ec713c46dda24a444fc01f7b57
