apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: posterizarr-secret
spec:
  target:
    name: posterizarr-secret

  secretStoreRef:
    name: openbao-store
    kind: ClusterSecretStore

  data:
    # ---- Discord ----
    - secretKey: DISCORD_WEBHOOK
      remoteRef:
        key: media/posterizarr
        property: DISCORD_WEBHOOK
    # ---- Fanart TV ----
    - secretKey: FANART_PERSONAL_API_KEY
      remoteRef:
        key: media/posterizarr
        property: FANART_PERSONAL_API_KEY
    # ---- Plex ----
    - secretKey: PLEX_TOKEN
      remoteRef:
        key: media/posterizarr
        property: PLEX_TOKEN
    # ---- TMDB ----
    - secretKey: TMDB_API_TOKEN
      remoteRef:
        key: media/posterizarr
        property: TMDB_API_TOKEN
    # ---- TVDB ----
    - secretKey: TVDB_API_KEY
      remoteRef:
        key: media/posterizarr
        property: TVDB_API_KEY