apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-store
  target:
    name: renovate-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      mergePolicy: Merge
      data:
        RENOVATE_HOST_RULES: |
          [
            {
              "matchHost": "docker.io",
              "username": "{{ .DOCKER_USERNAME }}",
              "password": "{{ .DOCKER_PASSWORD }}",
              "concurrentRequestLimit": 4
            },
            {
              "matchHost": "dhi.io",
              "username": "{{ .DOCKER_USERNAME }}",
              "password": "{{ .DOCKER_PASSWORD }}",
              "concurrentRequestLimit": 2
            },
            {
              "matchHost": "registry.k8s.io",
              "concurrentRequestLimit": 2
            },
            {
              "hostType": "docker",
              "matchHost": "ghcr.io",
              "username": "{{ .GHCR_USERNAME }}",
              "password": "{{ .GHCR_TOKEN }}"
            }
          ]
  data:
    - secretKey: RENOVATE_PRIVATE_KEY
      remoteRef:
        key: automation/renovate
        property: RENOVATE_PRIVATE_KEY
    - secretKey: RENOVATE_WEBHOOK_SECRET
      remoteRef:
        key: automation/renovate
        property: RENOVATE_WEBHOOK_SECRET
    - secretKey: RENOVATE_LICENSE_KEY
      remoteRef:
        key: automation/renovate
        property: RENOVATE_LICENSE_KEY
    - secretKey: DOCKER_USERNAME
      remoteRef:
        key: automation/renovate
        property: DOCKER_USERNAME
    - secretKey: DOCKER_PASSWORD
      remoteRef:
        key: automation/renovate
        property: DOCKER_PASSWORD
    - secretKey: GHCR_USERNAME
      remoteRef:
        key: automation/renovate
        property: GHCR_USERNAME
    - secretKey: GHCR_TOKEN
      remoteRef:
        key: automation/renovate
        property: GHCR_TOKEN
    - secretKey: DEFAULT_PR_REVIEWERS
      remoteRef:
        key: automation/renovate
        property: DEFAULT_PR_REVIEWERS
