apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: automation
resources:
  - env-configmap.yaml
  - external-secret.yaml
  - network-policy.yaml
  - redis.yaml
  - deployment.yaml
  - service.yaml
  - http-route.yaml
  - rate-limit.yaml

images:
  - name: ghcr.io/mend/renovate-ce
    newTag: 15.2.0@sha256:a18eff96e66955354a8aecfd692c67cd485afa266693f0e26253ec6e24e5c594
  - name: redis
    newTag: 8.10.0@sha256:344e3945a0b431c8ff1eecd58c5573538126bd756f02fc7e218ddf1fc2546366
