apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: automation
resources:
  - env-configmap.yaml
  - external-secret.yaml
  - network-policy.yaml
  - redis.yaml
  - deployment.yaml
  - service.yaml
  - http-route.yaml
  - rate-limit.yaml

images:
  - name: ghcr.io/mend/renovate-ce
    newTag: 14.6.0@sha256:09526a04669329ae551fd0fb2e3f5d46ee133c4d8582b43e9dbf49752075fda6
  - name: redis
    newTag: 8.8.0@sha256:aa049e689e141a4358ad1d4562dc49c88a89fbab711fd8fcc33f684c80b26301
