apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: automation
resources:
  - env-configmap.yaml
  - external-secret.yaml
  - network-policy.yaml
  - redis.yaml
  - deployment.yaml
  - service.yaml
  - http-route.yaml

images:
  - name: ghcr.io/mend/renovate-ce
    newTag: 14.5.0@sha256:7a985ff42ab9f513fe6ab559794fd8015c6ed4b1788cf51d48f42d4a2ebe6c42
  - name: redis
    newTag: 8.6.3@sha256:39d46d58c878f7bc0b6b8e9a4d9ee9995ede84bcf9762956df92987d0b394667
