apiVersion: v1
kind: Service
metadata:
  name: renovate-redis
  labels:
    app: renovate-redis
spec:
  ports:
    - name: redis
      port: 6379
      targetPort: redis
  selector:
    app: renovate-redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: renovate-redis
  labels:
    app: renovate-redis
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: renovate-redis
  template:
    metadata:
      labels:
        app: renovate-redis
    spec:
      containers:
        - name: dragonfly
          image: ghcr.io/dragonflydb/dragonfly
          args:
            - "--dbfilename=dump"
            - "--dir=/data"
            - "--proactor_threads=1"
            - "--snapshot_cron=*/15 * * * *"
            - "--force_epoll"
            - "--version_check=false"
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: redis
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: redis
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: "20m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "1024Mi"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - name: data
              mountPath: /data
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      volumes:
        - name: data
          emptyDir: {}
