apiVersion: v1
kind: Service
metadata:
  name: renovate-server
  namespace: automation
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: http-api
  selector:
    app: renovate-server
