apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jellyfin-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-store

  target:
    name: jellyfin-secrets
    creationPolicy: Owner

  data:
    - secretKey: LDAP_BIND_PASSWORD
      remoteRef:
        key: media/jellyfin
        property: LDAP_BIND_PASSWORD
    - secretKey: LDAP_BIND_DN
      remoteRef:
        key: media/jellyfin
        property: LDAP_BIND_DN
    - secretKey: LDAP_BASE_DN
      remoteRef:
        key: media/jellyfin
        property: LDAP_BASE_DN
