apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jellyfin-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vaultwarden-fields

  target:
    name: jellyfin-secrets
    creationPolicy: Owner

  data:
    - secretKey: LDAP_BIND_PASSWORD
      remoteRef:
        key: f01c0a38-17ef-4135-b6f2-39ece22ae5ff
        property: LDAP_PASSWORD
    - secretKey: LDAP_BIND_DN
      remoteRef:
        key: f01c0a38-17ef-4135-b6f2-39ece22ae5ff
        property: LDAP_BIND_DN
    - secretKey: LDAP_BASE_DN
      remoteRef:
        key: f01c0a38-17ef-4135-b6f2-39ece22ae5ff
        property: LDAP_BASE_DN
