apiVersion: v1
kind: Service
metadata:
  name: jellyfin-ui
  labels:
    pool: internal-lb-pool
  annotations:
    lbipam.cilium.io/ips: "10.10.1.132"
spec:
  type: LoadBalancer
  selector:
    app: jellyfin
  ports:
    - name: web-ui
      port: 8096
      targetPort: web-ui
---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin-discovery
spec:
  selector:
    app: jellyfin
  ports:
    - name: auto-discovery
      protocol: UDP
      port: 7359
      targetPort: 7359
    - name: dlna
      protocol: UDP
      port: 1900
      targetPort: 1900
