apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: media
resources:
  - secret.yaml
  - network-policies.yaml
  - cronjob.yaml

configMapGenerator:
  - name: kometa-config
    files:
      - config.yml=templates/config.yml
  - name: kometa-anime-config
    files:
      - anime.yaml=templates/anime.yaml
  - name: kometa-movie-config
    files:
      - movies.yaml=templates/movies.yaml
  - name: kometa-overlay-config
    files:
      - overlay.yaml=templates/overlay.yaml
  - name: kometa-tv-config
    files:
      - tv.yaml=templates/tv.yaml

generatorOptions:
  disableNameSuffixHash: true

labels:
  - pairs:
      app.kubernetes.io/name: kometa
      app.kubernetes.io/part-of: media-services
images:
  - name: alpine/k8s
    newTag: 1.35.2@sha256:9a87b09e1b6d887fa52c2dea1611d112d9e7d3d0271708588711a2fb2016e82c
  - name: kometateam/kometa
    newTag: v2.3.0@sha256:340e4176e1d75f04d2b55ce177326710f28770b5f56537fd539a034b143fe66d
