apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: media
resources:
  - secret.yaml
  - network-policies.yaml
  - cronjob.yaml

configMapGenerator:
  - name: kometa-config
    files:
      - config.yml=templates/config.yml
  - name: kometa-anime-config
    files:
      - anime.yaml=templates/anime.yaml
  - name: kometa-movie-config
    files:
      - movies.yaml=templates/movies.yaml
  - name: kometa-overlay-config
    files:
      - overlay.yaml=templates/overlay.yaml
  - name: kometa-tv-config
    files:
      - tv.yaml=templates/tv.yaml

generatorOptions:
  disableNameSuffixHash: true

labels:
  - pairs:
      app.kubernetes.io/name: kometa
      app.kubernetes.io/part-of: media-services
images:
  - name: alpine/k8s
    newTag: 1.36.0@sha256:c105e4eaa265c617e43be34fffc7d9961de76b65a1e520179ed61e2f3a9fabf7
  - name: kometateam/kometa
    newTag: v2.3.1@sha256:683c04827ef3fecf1cc5cb178f75f91f968aef6c6d89d34bc9c70966fd1d7259
