apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kometa-secrets
spec:
  target:
    name: kometa-secrets

  secretStoreRef:
    name: openbao-store
    kind: ClusterSecretStore

  data:
    # ---- AniDB ----
    - secretKey: ANIDB_PASSWORD
      remoteRef:
        key: media/kometa
        property: ANIDB_PASSWORD
    # ---- MyAnimeList ----
    - secretKey: MAL_ACCESS_TOKEN
      remoteRef:
        key: media/kometa
        property: MAL_ACCESS_TOKEN
    - secretKey: MAL_CLIENT_ID
      remoteRef:
        key: media/kometa
        property: MAL_CLIENT_ID
    - secretKey: MAL_CLIENT_SECRET
      remoteRef:
        key: media/kometa
        property: MAL_CLIENT_SECRET
    - secretKey: MAL_LOCALHOST_URL_CODE
      remoteRef:
        key: media/kometa
        property: MAL_LOCALHOST_URL_CODE
    - secretKey: MAL_REFRESH_TOKEN
      remoteRef:
        key: media/kometa
        property: MAL_REFRESH_TOKEN
    # ---- OMDB ----
    - secretKey: OMDB_API_KEY
      remoteRef:
        key: media/kometa
        property: OMDB_API_KEY
    # ---- Plex ----
    - secretKey: PLEX_TOKEN
      remoteRef:
        key: media/kometa
        property: PLEX_TOKEN
    # ---- Radarr ----
    - secretKey: RADARR_TOKEN
      remoteRef:
        key: media/kometa
        property: RADARR_TOKEN
    # ---- Sonarr ----
    - secretKey: SONARR_TOKEN
      remoteRef:
        key: media/kometa
        property: SONARR_TOKEN
    # ---- Tautulli ----
    - secretKey: TAUTULLI_API_KEY
      remoteRef:
        key: media/kometa
        property: TAUTULLI_API_KEY
    # ---- TMDB ----
    - secretKey: TMDB_API_KEY
      remoteRef:
        key: media/kometa
        property: TMDB_API_KEY
    # ---- Trakt ----
    - secretKey: TRAKT_ACCESS_TOKEN
      remoteRef:
        key: media/kometa
        property: TRAKT_ACCESS_TOKEN
    - secretKey: TRAKT_CLIENT_ID
      remoteRef:
        key: media/kometa
        property: TRAKT_CLIENT_ID
    - secretKey: TRAKT_CLIENT_SECRET
      remoteRef:
        key: media/kometa
        property: TRAKT_CLIENT_SECRET
    - secretKey: TRAKT_REFRESH_TOKEN
      remoteRef:
        key: media/kometa
        property: TRAKT_REFRESH_TOKEN
    - secretKey: NTFY_TOKEN
      remoteRef:
        key: media/kometa
        property: NTFY_TOKEN