apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: games

resources:
  - configmap.yaml
  - backup-script.yaml
  - statefulset.yaml
  - network-policy.yaml
  - service.yaml
  - storage.yaml
  - restore-job.yaml

images:
  - name: alpine
    newTag: 3.23.3@sha256:25109184c71bdad752c8312a8623239686a9a2071e8825f20acb8f2198c3f659
  - name: ghcr.io/itzg/minecraft-server
    newTag: java25@sha256:9b3dbabc31bb90abe1c9f7074d4b791cd429df69323ad247ff44f1ea609d73ff
