apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: games

resources:
  - configmap.yaml
  - backup-script.yaml
  - statefulset.yaml
  - network-policy.yaml
  - service.yaml
  - storage.yaml
  - restore-job.yaml

images:
  - name: alpine
    newTag: 3.24.0@sha256:a2d49ea686c2adfe3c992e47dc3b5e7fa6e6b5055609400dc2acaeb241c829f4
  - name: ghcr.io/itzg/minecraft-server
    newTag: java25@sha256:d54e9c99dfc77b18c02b896772798884b430f8e65865e785a2f5a9780d566320
