apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: games

resources:
  - configmap.yaml
  - backup-script.yaml
  - statefulset.yaml
  - network-policy.yaml
  - service.yaml
  - storage.yaml
  - restore-job.yaml

images:
  - name: alpine
    newTag: 3.24.1@sha256:28bd5fe8b56d1bd048e5babf5b10710ebe0bae67db86916198a6eec434943f8b
  - name: ghcr.io/itzg/minecraft-server
    newTag: java25@sha256:b0af6e8d44bdd6e5c513056a53631f5e69f08ba464d3d5c591b2e19fec9a43f9
