apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - http-route.yaml
  - network-policy.yaml
  - secret.yaml
  - configmap.yaml

labels:
  - pairs:
      app.kubernetes.io/name: seerr
      app.kubernetes.io/part-of: media-services
images:
  - name: ghcr.io/seerr-team/seerr
    newTag: v3.1.1@sha256:d535391db3b5a22ce02241e6d7a50ca714e75d927e46aa20456b77fa051cbf52
