apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - http-route.yaml
  - network-policy.yaml
  - secret.yaml
  - configmap.yaml

labels:
  - pairs:
      app.kubernetes.io/name: seerr
      app.kubernetes.io/part-of: media-services
images:
  - name: ghcr.io/seerr-team/seerr
    newTag: v3.2.0@sha256:c4cbd5121236ac2f70a843a0b920b68a27976be57917555f1c45b08a1e6b2aad
