apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - http-route.yaml
  - network-policy.yaml
  - secret.yaml
  - configmap.yaml

labels:
  - pairs:
      app.kubernetes.io/name: seerr
      app.kubernetes.io/part-of: media-services
images:
  - name: ghcr.io/seerr-team/seerr
    newTag: v3.3.0@sha256:c92d2dc117f62185e7bcb88cd56efd374ea79210eaf433275449e8d5988eb5a8
