apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: seerr-external-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-store

  target:
    name: seerr-secrets
    creationPolicy: Owner

  data:
    - secretKey: DB_USER
      remoteRef:
        key: media/seerr
        property: DB_USER
    - secretKey: DB_PASS
      remoteRef:
        key: media/seerr
        property: DB_PASS
    - secretKey: DB_HOST
      remoteRef:
        key: media/seerr
        property: DB_HOST
    - secretKey: DB_PORT
      remoteRef:
        key: media/seerr
        property: DB_PORT
