apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: seerr-external-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vaultwarden-fields

  target:
    name: seerr-secrets
    creationPolicy: Owner

  data:
    - secretKey: DB_USER
      remoteRef:
        key: 519f53d8-c5ff-44b6-b029-f16fed3a5d3d
        property: postgres_user
    - secretKey: DB_PASS
      remoteRef:
        key: 519f53d8-c5ff-44b6-b029-f16fed3a5d3d
        property: postgres_password
    - secretKey: DB_HOST
      remoteRef:
        key: 519f53d8-c5ff-44b6-b029-f16fed3a5d3d
        property: postgres_host
    - secretKey: DB_PORT
      remoteRef:
        key: 519f53d8-c5ff-44b6-b029-f16fed3a5d3d
        property: postgres_port
