apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-backup-nfs
  labels:
    pv-name: plex-backup-nfs
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4.1
    - async
    - noatime
    - rsize=1048576
    - wsize=1048576
    - hard
  nfs:
    server: fortress.kerrlab.app
    path: /volume1/cluster/media/plex/backup
  storageClassName: synostorage-nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-backup-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  selector:
    matchLabels:
      pv-name: plex-backup-nfs
  storageClassName: synostorage-nfs
