apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
        networking/expose-web-ui: "true"
    spec:
      initContainers:
        - name: inject-secrets
          image: hairyhenderson/gomplate
          command: [ "gomplate", "-f", "/template/config.xml", "-o", "/config/config.xml" ]
          envFrom:
            - secretRef:
                name: sonarr-secrets
          volumeMounts:
            - name: sonarr-template-vol
              mountPath: /template
            # Mount the Longhorn volume into the init container
            - name: sonarr-config-pvc
              mountPath: /config
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
      containers:
        - name: sonarr
          image: ghcr.io/home-operations/sonarr
          env:
            - name: PGID
              value: "100"
            - name: PUID
              value: "1027"
            - name: TZ
              value: "Europe/Chisinau"
          ports:
            - name: web-ui
              containerPort: 8989
              protocol: TCP
          startupProbe:
            httpGet:
              path: /ping
              port: web-ui
            failureThreshold: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ping
              port: web-ui
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /ping
              port: web-ui
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          resources:
            requests:
              cpu: 10m
              memory: 250Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          volumeMounts:
            - name: downloads-mount
              mountPath: /downloads # Path inside the container
            - name: video-series-mount
              mountPath: /tv # Path inside the container
            - name: video-anime-mount
              mountPath: /anime
            - name: video-movies-mount
              mountPath: /movies
            - name: sonarr-config-pvc
              mountPath: /config
          securityContext:
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
      securityContext:
        fsGroupChangePolicy: OnRootMismatch
        fsGroup: 100
        runAsGroup: 100
        runAsNonRoot: true
        runAsUser: 1027
      volumes:
        - name: downloads-mount
          persistentVolumeClaim:
            claimName: downloads-pvc
        - name: video-movies-mount
          persistentVolumeClaim:
            claimName: video-movies-pvc
        - name: video-series-mount
          persistentVolumeClaim:
            claimName: video-series-pvc
        - name: video-anime-mount
          persistentVolumeClaim:
            claimName: video-anime-pvc
        - name: sonarr-template-vol
          configMap:
            name: sonarr-config-template
        - name: sonarr-config-pvc
          persistentVolumeClaim:
            claimName: sonarr-config-longhorn-pvc
