apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment-tv.yaml
  - deployment-anime.yaml
  - service.yaml
  - http-route.yaml
  - network-policy.yaml
  - secret-tv.yaml
  - secret-anime.yaml

labels:
  - pairs:
      app.kubernetes.io/name: sonarr
      app.kubernetes.io/part-of: media-services
images:
  - name: ghcr.io/home-operations/sonarr
    newTag: 4.0.18@sha256:d0f2a003abfe9d9847931522778722deb05ed87da11d621818065d34e655a59b
  - name: ghcr.io/hononeko/k8s-config-tools
    newTag: 0.1.1@sha256:fb03e8e7910a51472309b361675f38da44ee398ab6ec64b020b660d4d0d4e400

# Shared config for both instances
configMapGenerator:
  - name: sonarr-tv-config-template
    files:
      - config.xml=templates/tv-config.xml
  - name: sonarr-anime-config-template
    files:
      - config.xml=templates/anime-config.xml
generatorOptions:
  disableNameSuffixHash: true
