apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment-tv.yaml
  - deployment-anime.yaml
  - service.yaml
  - http-route.yaml
  - network-policy.yaml
  - secret-tv.yaml
  - secret-anime.yaml

labels:
  - pairs:
      app.kubernetes.io/name: sonarr
      app.kubernetes.io/part-of: media-services
images:
  - name: ghcr.io/home-operations/sonarr
    newTag: 4.0.17@sha256:83607d2b741ec9469db09489e88c473ae6fdf7d85f3b55d4fa809b43e25a2a6c
  - name: hairyhenderson/gomplate
    newTag: v5.0-alpine@sha256:e9f830456c24b92dc8f59591d9604c90af6b7102c503f9834e716eb1002440e9

# Shared config for both instances
configMapGenerator:
  - name: sonarr-tv-config-template
    files:
      - config.xml=templates/tv-config.xml
  - name: sonarr-anime-config-template
    files:
      - config.xml=templates/anime-config.xml
generatorOptions:
  disableNameSuffixHash: true
