apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sonarr-external-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vaultwarden-fields

  target:
    name: sonarr-secrets
    creationPolicy: Owner

  data:
    - secretKey: SONARR_API_KEY
      remoteRef:
        key: 8efae41c-bce9-4cdd-8c08-966c2e1bd589
        property: api_key
    - secretKey: POSTGRES_USER
      remoteRef:
        key: 8efae41c-bce9-4cdd-8c08-966c2e1bd589
        property: postgres_user
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: 8efae41c-bce9-4cdd-8c08-966c2e1bd589
        property: postgres_password
    - secretKey: POSTGRES_PORT
      remoteRef:
        key: 8efae41c-bce9-4cdd-8c08-966c2e1bd589
        property: postgres_port
    - secretKey: POSTGRES_HOST
      remoteRef:
        key: 8efae41c-bce9-4cdd-8c08-966c2e1bd589
        property: postgres_host
    - secretKey: POSTGRES_MAIN_DB
      remoteRef:
        key: 8efae41c-bce9-4cdd-8c08-966c2e1bd589
        property: postgres_main_db
    - secretKey: POSTGRES_LOG_DB
      remoteRef:
        key: 8efae41c-bce9-4cdd-8c08-966c2e1bd589
        property: postgres_log_db