apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sonarr-anime-external-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-store

  target:
    name: sonarr-anime-secrets
    creationPolicy: Owner

  data:
    - secretKey: SONARR_API_KEY
      remoteRef:
        key: media/sonarr-anime
        property: SONARR_API_KEY
    - secretKey: POSTGRES_USER
      remoteRef:
        key: media/sonarr-anime
        property: POSTGRES_USER
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: media/sonarr-anime
        property: POSTGRES_PASSWORD
    - secretKey: POSTGRES_PORT
      remoteRef:
        key: media/sonarr-anime
        property: POSTGRES_PORT
    - secretKey: POSTGRES_HOST
      remoteRef:
        key: media/sonarr-anime
        property: POSTGRES_HOST
    - secretKey: POSTGRES_MAIN_DB
      remoteRef:
        key: media/sonarr-anime
        property: POSTGRES_MAIN_DB
    - secretKey: POSTGRES_LOG_DB
      remoteRef:
        key: media/sonarr-anime
        property: POSTGRES_LOG_DB