apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sonarr-anime-external-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vaultwarden-fields

  target:
    name: sonarr-anime-secrets
    creationPolicy: Owner

  data:
    - secretKey: SONARR_API_KEY
      remoteRef:
        key: 0e85eec4-7325-424d-b96c-30a2b3c40c79
        property: api_key
    - secretKey: POSTGRES_USER
      remoteRef:
        key: 0e85eec4-7325-424d-b96c-30a2b3c40c79
        property: postgres_user
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: 0e85eec4-7325-424d-b96c-30a2b3c40c79
        property: postgres_password
    - secretKey: POSTGRES_PORT
      remoteRef:
        key: 0e85eec4-7325-424d-b96c-30a2b3c40c79
        property: postgres_port
    - secretKey: POSTGRES_HOST
      remoteRef:
        key: 0e85eec4-7325-424d-b96c-30a2b3c40c79
        property: postgres_host
    - secretKey: POSTGRES_MAIN_DB
      remoteRef:
        key: 0e85eec4-7325-424d-b96c-30a2b3c40c79
        property: postgres_main_db
    - secretKey: POSTGRES_LOG_DB
      remoteRef:
        key: 0e85eec4-7325-424d-b96c-30a2b3c40c79
        property: postgres_log_db