apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tofu-sync-secrets
  namespace: tofu-sync
  labels:
    app.kubernetes.io/name: tofu-sync
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vaultwarden-fields
  target:
    name: tofu-sync-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        RCLONE_CONFIG_R2_TYPE: "s3"
        RCLONE_CONFIG_R2_PROVIDER: "Cloudflare"
        RCLONE_CONFIG_R2_ENDPOINT: "{{ .R2_ENDPOINT }}"
        RCLONE_CONFIG_R2_ACCESS_KEY_ID: "{{ .R2_ACCESS_KEY_ID }}"
        RCLONE_CONFIG_R2_SECRET_ACCESS_KEY: "{{ .R2_SECRET_ACCESS_KEY }}"
        RCLONE_CONFIG_R2_REGION: "auto"

        RCLONE_CONFIG_SEAWEEDFS_TYPE: "s3"
        RCLONE_CONFIG_SEAWEEDFS_PROVIDER: "Other"
        RCLONE_CONFIG_SEAWEEDFS_ENDPOINT: "https://s3.kerrlab.app"
        RCLONE_CONFIG_SEAWEEDFS_ACCESS_KEY_ID: "{{ .SW_ACCESS_KEY_ID }}"
        RCLONE_CONFIG_SEAWEEDFS_SECRET_ACCESS_KEY: "{{ .SW_SECRET_ACCESS_KEY }}"
        RCLONE_CONFIG_SEAWEEDFS_REGION: "us-east-1"
  data:
    - secretKey: R2_ENDPOINT
      remoteRef:
        key: "29608c30-6033-40b0-91a0-90ebc2dc4981"
        property: ENDPOINT
    - secretKey: R2_ACCESS_KEY_ID
      remoteRef:
        key: "29608c30-6033-40b0-91a0-90ebc2dc4981"
        property: ACCESS_KEY_ID
    - secretKey: R2_SECRET_ACCESS_KEY
      remoteRef:
        key: "29608c30-6033-40b0-91a0-90ebc2dc4981"
        property: SECRET_ACCESS_KEY
    - secretKey: SW_ACCESS_KEY_ID
      remoteRef:
        key: "bb7d5c3e-2ff7-4a42-a63b-0f86e5337b81"
        property: AWS_ACCESS_KEY_ID
    - secretKey: SW_SECRET_ACCESS_KEY
      remoteRef:
        key: "bb7d5c3e-2ff7-4a42-a63b-0f86e5337b81"
        property: AWS_SECRET_ACCESS_KEY
