---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keeper-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao-store
    kind: ClusterSecretStore
  target:
    name: keeper-secrets
    creationPolicy: Owner
  data:
    - secretKey: BETTER_AUTH_SECRET
      remoteRef:
        key: tools/keeper
        property: BETTER_AUTH_SECRET
    - secretKey: ENCRYPTION_KEY
      remoteRef:
        key: tools/keeper
        property: ENCRYPTION_KEY
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: tools/keeper
        property: POSTGRES_PASSWORD
