---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tools

labels:
  - pairs:
      app.kubernetes.io/name: keeper

resources:
  - configmap.yaml
  - external-secrets.yaml
  - valkey.yaml
  - deployment.yaml
  - service.yaml
  - http-route.yaml
  - external-http-route.yaml
  - rate-limit.yaml
  - network-policy.yaml

images:
  - name: ghcr.io/ridafkih/keeper-services
    newTag: 2.24.3@sha256:f4e4ebdc3c6557a5627a1701f80f72e25ac00d928c713bea240659f3f552aca5
  - name: ghcr.io/ridafkih/keeper-mcp
    newTag: 2.24.5@sha256:4c77d64512127b4a5169e06df1512b80e52d17c3692ae84c2401280e033aadd7
  - name: docker.io/valkey/valkey
    newTag: 9.1.2@sha256:418652cfb58ef879d4978c33553735d7147016032d5aefaa14c828e611eb9dfd
