---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tools

labels:
  - pairs:
      app.kubernetes.io/name: keeper

resources:
  - configmap.yaml
  - external-secrets.yaml
  - valkey.yaml
  - deployment.yaml
  - service.yaml
  - http-route.yaml
  - external-http-route.yaml
  - rate-limit.yaml
  - network-policy.yaml

images:
  - name: ghcr.io/ridafkih/keeper-services
    newTag: 2.24.1@sha256:41b2e63f50cf996416703317478c61c1af1ae0d36892f062a60598b884bfdaa5
  - name: ghcr.io/ridafkih/keeper-mcp
    newTag: 2.24.2@sha256:bdbd07e8466fb0dd97effff76fce9bb29a8d858190e04026226e1cf6c6b596e0
  - name: docker.io/valkey/valkey
    newTag: 9.1.2@sha256:418652cfb58ef879d4978c33553735d7147016032d5aefaa14c828e611eb9dfd
