apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - statefulset.yaml
  - service.yaml
  - http-route.yaml
  - external-http-route.yaml
  - rate-limit.yaml
  - network-policy.yaml
images:
  - name: busybox
    newTag: 1.37@sha256:b3255e7dfbcd10cb367af0d409747d511aeb66dfac98cf30e97e87e4207dd76f
  - name: docker.n8n.io/n8nio/n8n
    newTag: 2.11.1@sha256:39c634d65cf8830fec21ae7b242419e57737c2b1a1498b8b8c7578a585cf7ada
