crds:
  enabled: true

config:
  enableGatewayAPI: true

dns01RecursiveNameservers: "1.1.1.1:53,8.8.8.8:53"

prometheus:
  servicemonitor:
    enabled: false

resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 128Mi

webhook:
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 128Mi

cainjector:
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 128Mi
