crds:
  enabled: true

config:
  enableGatewayAPI: true

dns01RecursiveNameservers: "1.1.1.1:53,8.8.8.8:53"

prometheus:
  servicemonitor:
    enabled: false

resources:
  requests:
    cpu: "10m"
    memory: "16Mi"
  limits:
    cpu: "50m"
    memory: "64Mi"

webhook:
  resources:
    requests:
      cpu: "10m"
      memory: "16Mi"
    limits:
      cpu: "50m"
      memory: "64Mi"

cainjector:
  resources:
    requests:
      cpu: "10m"
      memory: "16Mi"
    limits:
      cpu: "50m"
      memory: "64Mi"
