apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - http-route.yaml
  - network-policy.yaml

labels:
  - pairs:
      app.kubernetes.io/name: bazarr
      app.kubernetes.io/part-of: media-services
images:
  - name: ghcr.io/home-operations/bazarr
    newTag: 1.5.6@sha256:79fc37491f55c7e24427bcd669bce3df2d7415ca432a47ce9d53cc5988af8411
