# Service to expose the Bar Assistant Backend internally
apiVersion: v1
kind: Service
metadata:
  name: bar-assistant
  namespace: home
  labels:
    app: bar-assistant
spec:
  selector:
    app: bar-assistant
  ports:
    - protocol: TCP
      name: http-api
      port: 8080
  type: ClusterIP
