apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home

labels:
  - pairs:
      app.kubernetes.io/name: bar-assistant

resources:
  - meilisearch-master-key.yaml
  - bar-assistant-config-map.yaml
  - bar-assistant-deployment.yaml
  - bar-assistant-service.yaml
  - http-route.yaml
  - salt-rim-deployment.yaml
  - salt-rim-service.yaml
  - network-policy.yaml
  - secret.yaml
  - middlewares.yaml
  - redis.yaml
  - redis-network-policy.yaml
  - external-http-route.yaml
  - rate-limit.yaml

images:
  - name: busybox
    newTag: 1.38@sha256:dc2d74b28e4cf8984fa52af1f39bc7c3d9c73760b41a74d629f5d11b1ab28616
  - name: ghcr.io/karlomikus/barassistant
    newTag: 6.5.0@sha256:08f5579bac77fa3d177c4382295cf3d1d699949c72529a0c8129697ad8e8383e
  - name: ghcr.io/karlomikus/salt-rim
    newTag: 5.4.0@sha256:b8aa1636b4c3e5a2b0c0a59ee8832ca294140c6c6a4aa3f04e2da185f9bea698
  - name: docker.io/valkey/valkey
    newTag: 9.1.2@sha256:a91d34ab33975b1054e26f1bd9995b268f7e0c507b5ded7f3d181a1a25521630
