apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home

labels:
  - pairs:
      app.kubernetes.io/name: bar-assistant

resources:
  - meilisearch-master-key.yaml
  - bar-assistant-config-map.yaml
  - bar-assistant-deployment.yaml
  - bar-assistant-service.yaml
  - http-route.yaml
  - salt-rim-deployment.yaml
  - salt-rim-service.yaml
  - network-policy.yaml
  - secret.yaml
  - middlewares.yaml
  - redis.yaml
  - redis-network-policy.yaml
  - external-http-route.yaml
  - rate-limit.yaml

images:
  - name: busybox
    newTag: 1.38@sha256:dc2d74b28e4cf8984fa52af1f39bc7c3d9c73760b41a74d629f5d11b1ab28616
  - name: ghcr.io/karlomikus/barassistant
    newTag: 5.15.4@sha256:f7a444e45999f901bd85df3c52bbe531af9c5ebc3b41786db40aa3134273f1f1
  - name: ghcr.io/karlomikus/salt-rim
    newTag: 4.15.0@sha256:2a764abf8bd1717257ec65db9cb4034406fc77968d46570a776004ca5ae2d192
