apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home

labels:
  - pairs:
      app.kubernetes.io/name: bar-assistant

resources:
  - meilisearch-master-key.yaml
  - bar-assistant-config-map.yaml
  - bar-assistant-deployment.yaml
  - bar-assistant-service.yaml
  - http-route.yaml
  - salt-rim-deployment.yaml
  - salt-rim-service.yaml
  - network-policy.yaml
  - secret.yaml
  - middlewares.yaml
  - redis.yaml
  - redis-network-policy.yaml

images:
  - name: busybox
    newTag: 1.37@sha256:1487d0af5f52b4ba31c7e465126ee2123fe3f2305d638e7827681e7cf6c83d5e
  - name: ghcr.io/karlomikus/barassistant
    newTag: 5.15.0@sha256:d48ba2aba91c25851228e650996489adf66049e7668dfebb9a0ee033656447ee
  - name: ghcr.io/karlomikus/salt-rim
    newTag: 4.15.0@sha256:2a764abf8bd1717257ec65db9cb4034406fc77968d46570a776004ca5ae2d192
