apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: bar-assistant-strip-prefix
spec:
  stripPrefix:
    prefixes:
      - /bar
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: bar-assistant-block-post-bars
spec:
  ipAllowList:
    sourceRange:
      - "127.0.0.1/32"

