apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bar-assistant-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vaultwarden-fields
    kind: ClusterSecretStore
  target:
    name: bar-assistant-secrets
    creationPolicy: Owner
  data:
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        key: "7a292775-3bf7-4e74-893d-b0c0499fa2b1"
        property: "OIDC_CLIENT_SECRET"
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: "7a292775-3bf7-4e74-893d-b0c0499fa2b1"
        property: "REDIS_PASSWORD"
  