apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - http-route.yaml
  - network-policy.yaml
  - secret.yaml

labels:
  - pairs:
      app.kubernetes.io/name: radarr
      app.kubernetes.io/part-of: media-services
images:
  - name: ghcr.io/home-operations/radarr
    newTag: 6.2.1@sha256:a566e7d364b96ce8ffb1b582266e656c69f3a12dec289d72bb0daa647ed4725e
  - name: ghcr.io/hononeko/k8s-config-tools
    newTag: 0.1.1@sha256:fb03e8e7910a51472309b361675f38da44ee398ab6ec64b020b660d4d0d4e400

configMapGenerator:
  - name: radarr-config-template
    files:
      - config.xml=templates/config.xml
generatorOptions:
  disableNameSuffixHash: true