apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tools
resources:
  - deployment.yaml
  - service.yaml
  - http-route.yaml
  - httpscaledobject.yaml
  - network-policy.yaml
images:
  - name: ghcr.io/thelounge/thelounge
    newTag: 4.5.2@sha256:c764151188d2c805932856ece9673917c868be38e22486d4fd9c5c376c663790
