apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tools
resources:
  - deployment.yaml
  - service.yaml
  - http-route.yaml
  - httpscaledobject.yaml
  - network-policy.yaml
images:
  - name: ghcr.io/thelounge/thelounge
    newTag: 4.5.2@sha256:79b02c2a8373063f300129729161ec75a26ea1881352845f01f12988075d378e
