apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tools
resources:
  - deployment.yaml
  - service.yaml
  - http-route.yaml
  - httpscaledobject.yaml
  - network-policy.yaml
images:
  - name: ghcr.io/thelounge/thelounge
    newTag: 4.5.0@sha256:d13e17cabb4e777eef5f8e31f78ef7ea1d75329a26f0998066f4e00f739a5433
