apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: iconify
spec:
  hosts:
    - iconify.kerrlab.app
  scaleTargetRef:
    name: iconify
    kind: Deployment
    apiVersion: apps/v1
    service: iconify
    port: 3000
  replicas:
    min: 0
    max: 1
