apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-store
  target:
    name: cloudflare-tunnel-credentials
    creationPolicy: Owner
  data:
    - secretKey: tunnel-token
      remoteRef:
        key: platform/cloudflare
        property: tunnel-token
