apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vaultwarden-fields
  target:
    name: cloudflare-tunnel-credentials
    creationPolicy: Owner
  data:
    - secretKey: tunnel-token
      remoteRef:
        key: "51e2f5af-0929-4ee7-ae77-06f0cff8a60f"
        property: token
