apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloudflare-tunnel

resources:
  - namespace.yaml
  - external-secret.yaml
  - deployment.yaml
  - network-policy.yaml
  - pdb.yaml

images:
  - name: cloudflare/cloudflared
    newTag: 2026.8.3@sha256:51c9cefcb4569df44e1ad403ab1d3d8065aa8e84339bcfc6aee75502e1140339
