apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloudflare-tunnel

resources:
  - namespace.yaml
  - external-secret.yaml
  - deployment.yaml
  - network-policy.yaml
  - pdb.yaml

images:
  - name: cloudflare/cloudflared
    newTag: 2026.9.3@sha256:072c067d25ccbe61d46e18f0d0723255f2bb5304f7317caa95b27031520ff92c
