apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloudflare-tunnel

resources:
  - namespace.yaml
  - external-secret.yaml
  - deployment.yaml
  - network-policy.yaml
  - pdb.yaml

images:
  - name: cloudflare/cloudflared
    newTag: 2026.9.0@sha256:ff69a2225ad7c6f85ed84fbd5f3087df46202426b2388ec60214098e0adf05e9
