apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cloudflared
spec:
  unhealthyPodEvictionPolicy: AlwaysAllow
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudflared
