apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: home-assistant
  template:
    metadata:
      labels:
        app: home-assistant
        networking/expose-web-ui: "true"
      annotations:
        k8s.v1.cni.cncf.io/networks: macvlan-iot
    spec:
      initContainers:
        - name: prepare-config
          image: hairyhenderson/gomplate
          command: [ "gomplate", "--left-delim", "[[", "--right-delim", "]]", "-f", "/template/configuration.yaml.template", "-o", "/config/configuration.yaml" ]
          volumeMounts:
            - name: config-template
              mountPath: /template
            - name: hass-data
              mountPath: /config
              subPath: config
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 50m
              memory: 64Mi
      containers:
        - name: homeassistant
          image: ghcr.io/home-operations/home-assistant
          ports:
            - containerPort: 8123
              name: web-ui
          volumeMounts:
            - name: hass-data
              mountPath: /config
              subPath: config
            - name: hass-data
              mountPath: /media
              subPath: media
          resources:
            requests:
              cpu: 10m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1024Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: false
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 65534
        fsGroupChangePolicy: OnRootMismatch
      volumes:
        - name: hass-data
          persistentVolumeClaim:
            claimName: home-assistant-pvc
        - name: config-template
          configMap:
            name: home-assistant-config
