apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: iot

labels:
  - pairs:
      app.kubernetes.io/name: home-assistant

resources:
  - deployment.yaml
  - service.yaml
  - http-route.yaml
  - nad.yaml
  - network-policy.yaml
images:
  - name: ghcr.io/home-operations/home-assistant
    newTag: 2026.3.4@sha256:45d37a8be32fc1b2ebc64acc9ab219ca6226dcf04b4de0046d6c4e650b7a3022
