apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: iot

labels:
  - pairs:
      app.kubernetes.io/name: home-assistant

resources:
  - deployment.yaml
  - service.yaml
  - http-route.yaml
  - compress-middleware.yaml
  - nad.yaml
  - network-policy.yaml

configMapGenerator:
  - name: home-assistant-config
    files:
      - configuration.yaml.template=template/configuration.yaml

generatorOptions:
  disableNameSuffixHash: true

images:
  - name: ghcr.io/home-operations/home-assistant
    newTag: 2026.9.0@sha256:f795a47fa14a5b109cc524b7f7e8b3d9ab95665d0482d9a11b794b6ad8425baa
  - name: ghcr.io/hononeko/k8s-config-tools
    newTag: 0.1.1@sha256:fb03e8e7910a51472309b361675f38da44ee398ab6ec64b020b660d4d0d4e400
