apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: iot

labels:
  - pairs:
      app.kubernetes.io/name: home-assistant

resources:
  - deployment.yaml
  - service.yaml
  - http-route.yaml
  - nad.yaml
  - network-policy.yaml

configMapGenerator:
  - name: home-assistant-config
    files:
      - configuration.yaml.template=template/configuration.yaml
      - pill_separator.yaml=template/pill_separator.yaml

generatorOptions:
  disableNameSuffixHash: true

images:
  - name: ghcr.io/home-operations/home-assistant
    newTag: 2026.9.4@sha256:c94ced77e2af72c605396b0c5636dd51528b8af6ad004a41990128845e2d682b
  - name: ghcr.io/hononeko/k8s-config-tools
    newTag: 0.1.1@sha256:fb03e8e7910a51472309b361675f38da44ee398ab6ec64b020b660d4d0d4e400
