apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: headlamp-egress
  namespace: observability
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: headlamp
  egress:
    # 1. Allow API Access (Critical)
    - toEntities:
        - kube-apiserver
        - host
        - remote-node
    - toCIDR:
        - 10.96.0.1/32
      toPorts:
        - ports:
            - port: "443"
              protocol: "TCP"

    # 3. Allow OIDC Provider (If you use Google/Dex/etc for login)
    - toEntities:
        - world
      toPorts:
        - ports:
            - port: "443"
              protocol: "TCP"