apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kaneo-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao-store
    kind: ClusterSecretStore
  target:
    name: kaneo-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        AUTH_SECRET: "{{ .AUTH_SECRET }}"
        POSTGRES_USER: "{{ .POSTGRES_USER }}"
        POSTGRES_PASSWORD: "{{ .POSTGRES_PASSWORD }}"
        DATABASE_URL: "postgresql://{{ .POSTGRES_USER }}:{{ .POSTGRES_PASSWORD }}@fortress.kerrlab.app:15432/kaneo"
        CUSTOM_OAUTH_CLIENT_SECRET: "{{ .CUSTOM_OAUTH_CLIENT_SECRET }}"
        S3_ACCESS_KEY_ID: "{{ .S3_ACCESS_KEY_ID }}"
        S3_SECRET_ACCESS_KEY: "{{ .S3_SECRET_ACCESS_KEY }}"
        GITHUB_APP_ID: "{{ .GITHUB_APP_ID }}"
        GITHUB_APP_NAME: "{{ .GITHUB_APP_NAME }}"
        GITHUB_WEBHOOK_SECRET: "{{ .GITHUB_WEBHOOK_SECRET }}"
        GITHUB_PRIVATE_KEY: "{{ .GITHUB_PRIVATE_KEY }}"
  data:
    - secretKey: AUTH_SECRET
      remoteRef:
        key: tools/kaneo
        property: AUTH_SECRET
    - secretKey: POSTGRES_USER
      remoteRef:
        key: tools/kaneo
        property: POSTGRES_USER
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: tools/kaneo
        property: POSTGRES_PASSWORD
    - secretKey: CUSTOM_OAUTH_CLIENT_SECRET
      remoteRef:
        key: tools/kaneo
        property: CUSTOM_OAUTH_CLIENT_SECRET
    - secretKey: S3_ACCESS_KEY_ID
      remoteRef:
        key: platform/s3/backup-filers
        property: AWS_ACCESS_KEY_ID
    - secretKey: S3_SECRET_ACCESS_KEY
      remoteRef:
        key: platform/s3/backup-filers
        property: AWS_SECRET_ACCESS_KEY
    - secretKey: GITHUB_APP_ID
      remoteRef:
        key: tools/kaneo
        property: GITHUB_APP_ID
    - secretKey: GITHUB_APP_NAME
      remoteRef:
        key: tools/kaneo
        property: GITHUB_APP_NAME
    - secretKey: GITHUB_WEBHOOK_SECRET
      remoteRef:
        key: tools/kaneo
        property: GITHUB_WEBHOOK_SECRET
    - secretKey: GITHUB_PRIVATE_KEY
      remoteRef:
        key: tools/kaneo
        property: GITHUB_PRIVATE_KEY
