apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tools

labels:
  - pairs:
      app.kubernetes.io/name: kaneo

resources:
  - configmap.yaml
  - external-secrets.yaml
  - deployment.yaml
  - service.yaml
  - http-route.yaml
  - external-http-route.yaml
  - rate-limit.yaml
  - network-policy.yaml
  - valkey.yaml

images:
  - name: ghcr.io/usekaneo/kaneo
    newTag: 2.26.0@sha256:549af9f6faf74825171badeda63db124461125bf9151425519b580513d4e4f5b
  - name: docker.io/valkey/valkey
    newTag: 9.1.2@sha256:418652cfb58ef879d4978c33553735d7147016032d5aefaa14c828e611eb9dfd
