apiVersion: apps/v1
kind: Deployment
metadata:
  name: go2rtc
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: go2rtc
  template:
    metadata:
      labels:
        app: go2rtc
        networking/expose-web-ui: "true"
      annotations:
        k8s.v1.cni.cncf.io/networks: macvlan-iot
    spec:
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 10.96.0.10
        searches:
          - iot.svc.cluster.local
          - svc.cluster.local
          - cluster.local
        options:
          - name: ndots
            value: "5"
      initContainers:
        - name: inject-secrets
          image: ghcr.io/hononeko/k8s-config-tools
          command: [ "gomplate", "-f", "/template/go2rtc.yaml", "-o", "/config/go2rtc.yaml" ]
          envFrom:
            - secretRef:
                name: go2rtc-vault-secrets
            - secretRef:
                name: go2rtc-fields-secrets
          volumeMounts:
            - name: go2rtc-template-vol
              mountPath: /template
            - name: go2rtc-config-dir
              mountPath: /config
          resources:
            requests:
              cpu: "10m"
              memory: "16Mi"
            limits:
              cpu: "50m"
              memory: "32Mi"
      containers:
        - name: go2rtc
          image: ghcr.io/alexxit/go2rtc
          ports:
            - containerPort: 1984
              name: web-ui
            - containerPort: 8554
              name: rtsp
            - containerPort: 8555
              name: webrtc
            - containerPort: 1935
              name: rtmp
          volumeMounts:
            - name: go2rtc-config-dir
              mountPath: /config
            - name: hass-data
              mountPath: /config/hass
              subPath: config
              readOnly: true
          resources:
            requests:
              cpu: "10m"
              memory: "32Mi"
            limits:
              cpu: "250m"
              memory: "128Mi"
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 65534
        fsGroupChangePolicy: OnRootMismatch
      volumes:
        - name: hass-data
          persistentVolumeClaim:
            claimName: home-assistant-pvc
        - name: go2rtc-template-vol
          configMap:
            name: go2rtc-config-template
        - name: go2rtc-config-dir
          emptyDir: {}
