apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: go2rtc-policy
spec:
  endpointSelector:
    matchLabels:
      app: go2rtc
  # ----=== Ingress ===----
  ingress:
    # === Allow access from Home Assistant ===
    - fromEndpoints:
        - matchLabels:
            app: home-assistant
      toPorts:
        - ports:
            - port: "http" # 1984
              protocol: TCP
    # === Allow access from local networks (Direct LB Access) ===
    - fromCIDR:
        - 192.168.1.0/24
        - 192.168.4.0/24
        - 10.10.1.0/24
      toPorts:
        - ports:
            - port: "webrtc" # 8555 TCP/UDP
              protocol: TCP
            - port: "webrtc" # 8555 TCP/UDP
              protocol: UDP
            - port: "rtsp"   # 8554 TCP
              protocol: TCP

  # ----=== Egress ===----
  egress:
    # === To Home Assistant ===
    - toServices:
        - k8sService:
            serviceName: home-assistant
            namespace: iot
      toPorts:
        - ports:
            - port: "8123"
              protocol: TCP
    # === Camera Ingestion (RTSP/HTTP to LAN) ===
    - toCIDR:
        - 192.168.0.0/16
        - 10.0.0.0/8
    # === STUN/ICE (UDP to World) ===
    # Required for WebRTC NAT traversal negotiation
    - toEntities:
        - "world"