apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: go2rtc-vault-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vaultwarden-store

  target:
    name: go2rtc-vault-secrets
    creationPolicy: Owner

  data:
    - secretKey: API_USERNAME
      remoteRef:
        key: 43af8601-145f-49c1-9283-a83f7ed40eb4
        property: username
    - secretKey: API_PASSWORD
      remoteRef:
        key: 43af8601-145f-49c1-9283-a83f7ed40eb4
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: go2rtc-fields-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vaultwarden-fields

  target:
    name: go2rtc-fields-secrets
    creationPolicy: Owner

  data:
    - secretKey: RTSP_PASSWORD
      remoteRef:
        key: 43af8601-145f-49c1-9283-a83f7ed40eb4
        property: RTSP_stream_password
