apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: go2rtc-vault-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-store

  target:
    name: go2rtc-vault-secrets
    creationPolicy: Owner

  data:
    - secretKey: API_USERNAME
      remoteRef:
        key: iot/go2rtc
        property: API_USERNAME
    - secretKey: API_PASSWORD
      remoteRef:
        key: iot/go2rtc
        property: API_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: go2rtc-fields-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-store

  target:
    name: go2rtc-fields-secrets
    creationPolicy: Owner

  data:
    - secretKey: RTSP_PASSWORD
      remoteRef:
        key: iot/go2rtc
        property: RTSP_PASSWORD
