apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cronjob.yml
  - secret.yml
  - network-policy.yml

labels:
  - pairs:
      app.kubernetes.io/name: recyclarr
      app.kubernetes.io/part-of: media-services

images:
  - name: ghcr.io/recyclarr/recyclarr
    newTag: 8.7.1@sha256:73303ba5ee647b6492fee917d3a781c6e59b6cab08f9dfce9482a950846f564f

configMapGenerator:
  - name: recyclarr-config
    files:
      - recyclarr.yml=templates/recyclarr.yml
generatorOptions:
  disableNameSuffixHash: true