apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cronjob.yml
  - secret.yml
  - network-policy.yml

labels:
  - pairs:
      app.kubernetes.io/name: recyclarr
      app.kubernetes.io/part-of: media-services

images:
  - name: ghcr.io/recyclarr/recyclarr
    newTag: 8.7.2@sha256:6e69e009e1cd7493ff6093e8e187b5d3788c75b4a2c0c5127b6a1beda1c19728

configMapGenerator:
  - name: recyclarr-config
    files:
      - recyclarr.yml=templates/recyclarr.yml
generatorOptions:
  disableNameSuffixHash: true