apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: recyclarr-external-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vaultwarden-fields

  target:
    name: recyclarr-secrets
    creationPolicy: Owner

  data:
    - secretKey: SONARR_TV_API_KEY
      remoteRef:
        key: 8efae41c-bce9-4cdd-8c08-966c2e1bd589
        property: api_key
    - secretKey: SONARR_ANIME_API_KEY
      remoteRef:
        key: 0e85eec4-7325-424d-b96c-30a2b3c40c79
        property: api_key
    - secretKey: RADARR_API_KEY
      remoteRef:
        key: f5a82ad7-3e61-4ca2-9577-bafeb4e7c4b0
        property: api_key