apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: recyclarr-external-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-store

  target:
    name: recyclarr-secrets
    creationPolicy: Owner

  data:
    - secretKey: SONARR_TV_API_KEY
      remoteRef:
        key: media/recyclarr
        property: SONARR_TV_API_KEY
    - secretKey: SONARR_ANIME_API_KEY
      remoteRef:
        key: media/recyclarr
        property: SONARR_ANIME_API_KEY
    - secretKey: RADARR_API_KEY
      remoteRef:
        key: media/recyclarr
        property: RADARR_API_KEY