apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - http-route.yaml
  - network-policy.yaml
  - hpa.yaml

labels:
  - pairs:
      app.kubernetes.io/name: flaresolverr
      app.kubernetes.io/part-of: media-services
images:
  - name: ghcr.io/flaresolverr/flaresolverr
    newTag: v3.5.2@sha256:c80ae007ce2ccdcd217a12426e4f039ef763ff90738c808d38810c3e59323767
