apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - http-route.yaml
  - network-policy.yaml
  - restore-job.yaml

configMapGenerator:
  - name: plex-backup-script
    files:
      - backup.sh=scripts/backup.sh
  - name: plex-restore-script
    files:
      - restore.sh=scripts/restore.sh

labels:
  - pairs:
      app.kubernetes.io/name: plex
      app.kubernetes.io/part-of: media-services
images:
  - name: plexinc/pms-docker
    newTag: 1.43.1.10576-06378bdcd@sha256:80c1c9080352613e77fc2f49bcfee67a0a72cd60b9cf4bbc1b601e55c0160859
