apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - http-route.yaml
  - network-policy.yaml
  - restore-job.yaml

configMapGenerator:
  - name: plex-backup-script
    files:
      - backup.sh=scripts/backup.sh
  - name: plex-restore-script
    files:
      - restore.sh=scripts/restore.sh

labels:
  - pairs:
      app.kubernetes.io/name: plex
      app.kubernetes.io/part-of: media-services
images:
  - name: plexinc/pms-docker
    newTag: 1.43.1.10611-1e34174b1@sha256:8b5bcdf7b506fe051aa1a0a0d464efdb3ad8c0fb1f8a4dfb27a8c489b609920c
