apiVersion: batch/v1
kind: CronJob
metadata:
  name: restore-plex-db
spec:
  suspend: true
  schedule: "@yearly"
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          securityContext:
            runAsUser: 0
          containers:
            - name: restorer
              image: alpine
              command: ["/bin/sh", "/scripts/restore.sh"]
              volumeMounts:
                - name: restore-script
                  mountPath: /scripts/restore.sh
                  subPath: restore.sh
                  readOnly: true
                - name: config
                  mountPath: /config
                - name: backups
                  mountPath: /backups
              resources:
                requests:
                  memory: "128Mi"
                  cpu: "100m"
                limits:
                  memory: "256Mi"
                  cpu: "200m"
          volumes:
            - name: restore-script
              configMap:
                name: plex-restore-script
                defaultMode: 0755
            - name: config
              persistentVolumeClaim:
                claimName: plex-config-longhorn-pvc
            - name: backups
              persistentVolumeClaim:
                claimName: plex-backup-pvc
          restartPolicy: Never
