apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: plex-secret
spec:
  target:
    name: plex-secret

  secretStoreRef:
    name: openbao-store
    kind: ClusterSecretStore

  data:
    # ---- Plex ----
    - secretKey: PLEX_CLAIM
      remoteRef:
        key: media/plex
        property: PLEX_CLAIM