apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: iot

labels:
  - pairs:
      app.kubernetes.io/name: matter-server

resources:
  - deployment.yaml
  - service.yaml
  - network-policy.yaml
  - http-route.yaml
images:
  - name: ghcr.io/matter-js/matterjs-server
    newTag: 1.2.8@sha256:cb5696f5d5584d63bcc22eea1565e21d0de9c41e86f212bf2fe5bce21f95897d
  - name: busybox
    newTag: 1.38.0@sha256:fd8d9aa63ba2f0982b5304e1ee8d3b90a210bc1ffb5314d980eb6962f1a9715d
