apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: iot

labels:
  - pairs:
      app.kubernetes.io/name: matter-server

resources:
  - deployment.yaml
  - service.yaml
  - network-policy.yaml
  - http-route.yaml
images:
  - name: ghcr.io/matter-js/matterjs-server
    newTag: 1.1.3@sha256:c136e497324890b307287db2e035cef5e844ac915ea3de7907e2838324c4478e
  - name: busybox
    newTag: 1.38.0@sha256:fd8d9aa63ba2f0982b5304e1ee8d3b90a210bc1ffb5314d980eb6962f1a9715d
