apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: iot

labels:
  - pairs:
      app.kubernetes.io/name: matter-server

resources:
  - deployment.yaml
  - service.yaml
  - network-policy.yaml
  - http-route.yaml
images:
  - name: ghcr.io/matter-js/matterjs-server
    newTag: 0.7.1@sha256:1935c641893cf25f0337dd1aa02af9ae0fa22fb50fe7fa274b4519adb2bb028b
  - name: busybox
    newTag: 1.37.0@sha256:0d3f1e630be52ade0c06107515937607be2cab11a2ad2122099fc79e19bcc18b
