apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: thelounge
  name: the-lounge-config-longhorn-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: longhorn-retain
  volumeMode: Filesystem
