apiVersion: v1
kind: Service
metadata:
  name: minecraft-voice
  labels:
    app: minecraft-vanilla
    pool: dmz-lb-pool
  annotations:
    lbipam.cilium.io/ips: "10.20.1.140"
    lbipam.cilium.io/sharing-key: "minecraft-games"
    cilium.io/service-sharing-key: "minecraft-games"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app: minecraft-vanilla
  ports:
    - name: voice-udp
      port: 24454
      targetPort: 24454
      protocol: UDP
