apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tools
resources:
  - deployment.yaml
  - service.yaml
  - http-route.yaml
  - httpscaledobject.yaml
  - network-policy.yaml
images:
  - name: ghcr.io/mermaid-js/mermaid-live-editor
    newTag: latest@sha256:633aed825ed18a30297da396fea176872196b2c302e585e6267e2993beb0bba8
