apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tools
resources:
  - deployment.yaml
  - service.yaml
  - http-route.yaml
  - httpscaledobject.yaml
  - network-policy.yaml
images:
  - name: ghcr.io/mermaid-js/mermaid-live-editor
    newTag: latest@sha256:c3a794fa338ab7638697abf46d6aa27dff8f2105dd0d45e3c2e0fa9fe20ad890
