apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tools
resources:
  - deployment.yaml
  - service.yaml
  - http-route.yaml
  - httpscaledobject.yaml
  - network-policy.yaml
images:
  - name: ghcr.io/mermaid-js/mermaid-live-editor
    newTag: latest@sha256:38c2af2079f6650a711c2f4b35c115510e527180ea769a1ca97a460d36445e7d
