apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: mermaid-policy
spec:
  endpointSelector:
    matchLabels:
      app: mermaid

  # Allow Ingress (Inbound)
  ingress:
    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: keda
            app.kubernetes.io/component: interceptor
      toPorts:
        - ports:
            - port: "8080"
              protocol: "TCP"
