apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability

helmCharts:
  - name: keda
    repo: https://kedacore.github.io/charts
    version: 2.19.0
    releaseName: keda
    namespace: observability
  - name: keda-add-ons-http
    repo: https://kedacore.github.io/charts
    version: 0.12.2
    releaseName: keda-add-ons-http
    namespace: observability

resources:
  - namespace.yaml
  - network-policy.yaml
  - reference-grant.yaml

patches:
  - patch: |-
      apiVersion: v1
      kind: Service
      metadata:
        name: keda-add-ons-http-interceptor-proxy
      spec:
        ipFamilyPolicy: PreferDualStack
        ipFamilies:
        - IPv6
        - IPv4
    target:
      kind: Service
      name: keda-add-ons-http-interceptor-proxy
