apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - http-route.yaml
  - network-policy.yaml

labels:
  - pairs:
      app.kubernetes.io/name: tautulli
      app.kubernetes.io/part-of: media-services
images:
  - name: ghcr.io/home-operations/tautulli
    newTag: 2.16.1@sha256:492b201778383bc58ef061dbd2584d9c0e5cfbd5090a1d48340b65589e26b144
