apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: automation

resources:
  - secrets.yaml
  - webserver.yaml
  - executor.yaml
  - worker.yaml
  - hpa.yaml
  - http-route.yaml
  - network-policy.yaml

configMapGenerator:
  - name: kestra-config
    files:
      - application.yml=templates/application.yml


images:
  - name: kestra/kestra
    newTag: v1.3.25@sha256:2289a0cd123e4b7a76661b486cdaaada42c1759502d09746b7930d1c8ca6d402
