apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: automation

resources:
  - secrets.yaml
  - webserver.yaml
  - executor.yaml
  - worker.yaml
  - hpa.yaml
  - http-route.yaml
  - network-policy.yaml

configMapGenerator:
  - name: kestra-config
    files:
      - application.yml=templates/application.yml


images:
  - name: kestra/kestra
    newTag: v1.3.22@sha256:a483256827fde054c5b4a903a8ae5a0057ddb791cfe6e31b9f6978b3917f346d
