apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: automation

resources:
  - secrets.yaml
  - webserver.yaml
  - executor.yaml
  - worker.yaml
  - hpa.yaml
  - http-route.yaml
  - network-policy.yaml

configMapGenerator:
  - name: kestra-config
    files:
      - application.yml=templates/application.yml


images:
  - name: kestra/kestra
    newTag: v1.3.26@sha256:956f128e7ed6665feb56eb007f4939514c5b25ed0500c74d405f11be1a6ac090
