apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kestra-credentials
  namespace: automation
spec:
  refreshInterval: 1h
  target:
    creationPolicy: Owner
    name: kestra-credentials
  data:
    - remoteRef:
        key: 1e3f5a3a-1bfd-4ab1-b1f5-ef5d52fefde1
        property: POSTGRES_PASSWORD
      secretKey: DB_PASSWORD
      sourceRef:
        storeRef:
          name: vaultwarden-fields
          kind: ClusterSecretStore
    - remoteRef:
        key: bb7d5c3e-2ff7-4a42-a63b-0f86e5337b81
        property: AWS_ACCESS_KEY_ID
      secretKey: MINIO_ACCESS_KEY
      sourceRef:
        storeRef:
          name: vaultwarden-fields
          kind: ClusterSecretStore
    - remoteRef:
        key: bb7d5c3e-2ff7-4a42-a63b-0f86e5337b81
        property: AWS_SECRET_ACCESS_KEY
      secretKey: MINIO_SECRET_KEY
      sourceRef:
        storeRef:
          name: vaultwarden-fields
          kind: ClusterSecretStore
