apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minecraft-create-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao-store
    kind: ClusterSecretStore
  target:
    name: minecraft-create-secret
    creationPolicy: Owner
  data:
    - secretKey: RCON_PASSWORD
      remoteRef:
        key: games/minecraft/create
        property: RCON_PASSWORD
