apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tools
resources:
  - deployment.yaml
  - service.yaml
  - http-route.yaml
  - rate-limit.yaml
  - httpscaledobject.yaml
  - network-policy.yaml
images:
  - name: traefik/whoami
    newTag: v1.12@sha256:c4717a8d1f0134a7444e24f881160e033991f23027c6c5a9a3f8fd22e70d1d44
