apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: whoami-policy
  namespace: default
spec:
  endpointSelector:
    matchLabels:
      app: whoami

  # Allow Ingress (Inbound)
  ingress:
    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: keda
            app.kubernetes.io/component: interceptor
      toPorts:
        - ports:
            - port: "80"
              protocol: "TCP"
