apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: client-info-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-store
  target:
    name: client-info-secret
    creationPolicy: Owner
    template:
      data:
        client-info.yml: |
          clients:
            - host: fortress.kerrlab.app
              port: 443
              https: true
              username: k8s-user
              password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: synology-csi/client-info
        property: password
