config:
  sessionTTL: null
  oidc:
    secret:
      create: false
    externalSecret:
      enabled: true
      name: headlamp-oidc-credentials
    scopes: "openid profile email groups"
    useAccessToken: false
    usePKCE: true
    useCookie: true
    issuerURL: "https://auth.kerrlab.app"
