apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: security

resources:
  - deployment.yaml
  - service.yaml
  - secret.yaml
  - http-route.yaml
  - network-policy.yaml
  - certificate.yaml

images:
  - name: ghcr.io/lldap/lldap
    newTag: stable-alpine-rootless@sha256:ba2c50930ea998eefd5454aa678a7977448019248b1827da87d330df0b71c284
