apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: lldap-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vaultwarden-fields
    kind: ClusterSecretStore
  target:
    name: lldap-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        LLDAP_DATABASE_URL: "postgres://{{ .postgres_user }}:{{ .postgres_password }}@{{ .postgres_host }}:{{ .postgres_port }}/{{ .postgres_db }}"
        LLDAP_JWT_SECRET: "{{ .jwt_secret }}"
        LLDAP_LDAP_USER_DN: "{{ .ldap_admin_user }}"
        LLDAP_LDAP_USER_PASS: "{{ .ldap_admin_password }}"
  data:
    - secretKey: postgres_user
      remoteRef:
        key: "691492f0-f237-4526-a2b5-6881521e17c1"
        property: "postgres_user"
    - secretKey: postgres_password
      remoteRef:
        key: "691492f0-f237-4526-a2b5-6881521e17c1"
        property: "postgres_password"
    - secretKey: postgres_host
      remoteRef:
        key: "691492f0-f237-4526-a2b5-6881521e17c1"
        property: "postgres_host"
    - secretKey: postgres_port
      remoteRef:
        key: "691492f0-f237-4526-a2b5-6881521e17c1"
        property: "postgres_port"
    - secretKey: postgres_db
      remoteRef:
        key: "691492f0-f237-4526-a2b5-6881521e17c1"
        property: "postgres_db"
    - secretKey: jwt_secret
      remoteRef:
        key: "691492f0-f237-4526-a2b5-6881521e17c1"
        property: "JWT_SECRET"
    - secretKey: ldap_admin_user
      remoteRef:
        key: "691492f0-f237-4526-a2b5-6881521e17c1"
        property: "admin_user"
    - secretKey: ldap_admin_password
      remoteRef:
        key: "691492f0-f237-4526-a2b5-6881521e17c1"
        property: "admin_password"
