apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-db-credentials
spec:
  refreshInterval: 1h
  target:
    creationPolicy: Owner
    name: n8n-db-credentials
  data:
    - remoteRef:
        key: 3819ee8a-d920-48a6-93f4-a47058e4783c
        property: POSTGRES_PASSWORD
      secretKey: DB_POSTGRESDB_PASSWORD
      sourceRef:
        storeRef:
          name: vaultwarden-fields
          kind: ClusterSecretStore
