apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-db-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao-store
    kind: ClusterSecretStore
  target:
    creationPolicy: Owner
    name: n8n-db-credentials
  data:
    - secretKey: DB_POSTGRESDB_PASSWORD
      remoteRef:
        key: automation/n8n
        property: DB_POSTGRESDB_PASSWORD
