apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: n8n-route
spec:
  parentRefs:
    - name: internal-gateway
      namespace: traefik
  hostnames:
    - "n8n.kerrlab.app"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: n8n-main
          port: 5678
    - matches:
        - path:
            type: PathPrefix
            value: /webhook
        - path:
            type: PathPrefix
            value: /webhook-test
        - path:
            type: PathPrefix
            value: /webhook-waiting
      backendRefs:
        - name: n8n-webhook-processor
          port: 5678
