apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: automation
helmCharts:
  - name: n8n
    repo: oci://ghcr.io/n8n-io/n8n-helm-chart
    version: 1.1.0 
    releaseName: n8n
    namespace: automation
    includeCRDs: true
    valuesFile: values/values.yml

resources:
  - configmap.yaml
  - secrets.yaml
  - db-credentials.yaml
  - http-route.yaml
  - external-http-route.yaml
  - rate-limit.yaml
  - network-policy.yaml
  - redis.yaml
  - redis-network-policy.yaml
images:
  - name: busybox
    newTag: 1.37@sha256:b3255e7dfbcd10cb367af0d409747d511aeb66dfac98cf30e97e87e4207dd76f
  - name: docker.n8n.io/n8nio/n8n
    newTag: 2.13.2@sha256:72e962537379dcefeb63a01397a099576e2e89a365f5a75efb8a5ad5bc5cff6a
