apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: automation
helmCharts:
  - name: n8n
    repo: oci://ghcr.io/n8n-io/n8n-helm-chart
    version: 1.11.0 
    releaseName: n8n
    namespace: automation
    includeCRDs: true
    valuesFile: values/values.yml

resources:
  - configmap.yaml
  - secrets.yaml
  - db-credentials.yaml
  - http-route.yaml
  - external-http-route.yaml
  - rate-limit.yaml
  - network-policy.yaml
  - redis.yaml
  - redis-network-policy.yaml
images:
  - name: busybox
    newTag: 1.38@sha256:dc2d74b28e4cf8984fa52af1f39bc7c3d9c73760b41a74d629f5d11b1ab28616
  - name: ghcr.io/n8n-io/n8n
    newTag: 2.37.6@sha256:97ce2e6bd5d7e4ff7c38620dde28f9465d8af3970463dd65f2546b56f1a3df25
  - name: docker.io/valkey/valkey
    newTag: 9.1.1@sha256:70739f85ad2ee01a726a965584a0f94895f01b0c60b3cc8b0aeef11eaa6888cf
patches:
  - path: hpa-patch.yaml
    target:
      kind: HorizontalPodAutoscaler
      name: n8n-webhook-processor
