apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: automation
helmCharts:
  - name: n8n
    repo: oci://ghcr.io/n8n-io/n8n-helm-chart
    version: 1.12.0 
    releaseName: n8n
    namespace: automation
    includeCRDs: true
    valuesFile: values/values.yml

resources:
  - configmap.yaml
  - secrets.yaml
  - db-credentials.yaml
  - http-route.yaml
  - external-http-route.yaml
  - rate-limit.yaml
  - network-policy.yaml
  - redis.yaml
  - redis-network-policy.yaml
images:
  - name: busybox
    newTag: 1.38@sha256:dc2d74b28e4cf8984fa52af1f39bc7c3d9c73760b41a74d629f5d11b1ab28616
  - name: ghcr.io/n8n-io/n8n
    newTag: 2.40.4@sha256:e78d46514fda1869378ec3caa1cc40e97eb71cf2f1d5e973d989ad80917e594c
  - name: docker.io/valkey/valkey
    newTag: 9.1.2@sha256:418652cfb58ef879d4978c33553735d7147016032d5aefaa14c828e611eb9dfd
patches:
  - path: hpa-patch.yaml
    target:
      kind: HorizontalPodAutoscaler
      name: n8n-webhook-processor
  - path: hpa-patch.yaml
    target:
      kind: HorizontalPodAutoscaler
      name: n8n-worker
  - patch: |-
      - op: remove
        path: /spec/replicas
    target:
      kind: Deployment
      name: n8n-worker
  - patch: |-
      - op: remove
        path: /spec/replicas
    target:
      kind: Deployment
      name: n8n-webhook-processor
