apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: n8n-policy
spec:
  endpointSelector:
    matchExpressions:
      - key: app.kubernetes.io/name
        operator: In
        values:
          - n8n
          - n8n-worker
  ingress:
    # === Allow access from Traefik ===
    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: traefik
            app.kubernetes.io/name: traefik
      toPorts:
        - ports:
            - port: "http"
              protocol: "TCP"
    # === Allow access from qBittorrent ===
    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: media
            app: qbittorrent
      toPorts:
        - ports:
            - port: "5678"
              protocol: TCP
  egress:
    # === Allow egress to Traefik (Hairpinning) ===
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: traefik
            app.kubernetes.io/name: traefik
      toPorts:
        - ports:
            - port: "websecure"
              protocol: TCP
            - port: "dmz"
              protocol: TCP

    # === Allow egress to NAS PostgreSQL ===
    - toCIDR:
        - "10.10.1.218/32"
      toPorts:
        - ports:
            - port: "15432"
              protocol: TCP

    # === Allow egress to Home Assistant ===
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: iot
            app: home-assistant
      toPorts:
        - ports:
            - port: "8123"
              protocol: TCP
    # === Allow egress to Redis ===
    - toEndpoints:
        - matchLabels:
            "k8s:app": "redis-n8n"
      toPorts:
        - ports:
            - port: "6379"
              protocol: TCP
    # === Allow egress to ntfy, sonarr, radarr ===
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: automation
            app.kubernetes.io/name: ntfy
      toPorts:
        - ports:
            - port: "80"
              protocol: TCP
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: media
            app: sonarr
      toPorts:
        - ports:
            - port: "8989"
              protocol: TCP
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: media
            app: radarr
      toPorts:
        - ports:
            - port: "7878"
              protocol: TCP
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: media
            app: qbittorrent
      toPorts:
        - ports:
            - port: "8080"
              protocol: TCP
    # === Allow Internet Access ===
    - toEntities:
        - "world"
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
