apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: n8n-redis-policy
spec:
  endpointSelector:
    matchExpressions:
      - key: "k8s:app"
        operator: "In"
        values:
          - "redis-n8n"
  ingress:
    - fromEndpoints:
        - matchExpressions:
            - key: "k8s:app"
              operator: "In"
              values:
                - "n8n"
                - "n8n-worker"
      toPorts:
        - ports:
            - port: "6379"
              protocol: "TCP"
    - fromEndpoints:
        - matchLabels:
            "k8s:name": "redis-operator"
            "k8s:io.kubernetes.pod.namespace": "data-services"
      toPorts:
        - ports:
            - port: "6379"
              protocol: "TCP"
