apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-secrets
spec:
  refreshInterval: 1h
  target:
    creationPolicy: Owner
    name: n8n-secrets
    template:
      type: Opaque
      data:
        N8N_PROTOCOL: "https"
        N8N_HOST: "n8n.kerrlab.app"
        N8N_PORT: "5678"
        N8N_LICENSE_ACTIVATION_KEY: "{{ .N8N_LICENSE_ACTIVATION_KEY }}"
        QUEUE_BULL_REDIS_PASSWORD: "{{ .QUEUE_BULL_REDIS_PASSWORD }}"
        N8N_ENCRYPTION_KEY: "{{ .N8N_ENCRYPTION_KEY }}"
        TASK_RUNNER_TOKEN: "{{ .TASK_RUNNER_TOKEN }}"
  data:
    - remoteRef:
        key: 3819ee8a-d920-48a6-93f4-a47058e4783c
        property: N8N_LICENSE_ACTIVATION_KEY
      secretKey: N8N_LICENSE_ACTIVATION_KEY
      sourceRef:
        storeRef:
          name: vaultwarden-fields
          kind: ClusterSecretStore
    - remoteRef:
        key: 3819ee8a-d920-48a6-93f4-a47058e4783c
        property: REDIS_PASSWORD
      secretKey: QUEUE_BULL_REDIS_PASSWORD
      sourceRef:
        storeRef:
          name: vaultwarden-fields
          kind: ClusterSecretStore
    - remoteRef:
        key: 3819ee8a-d920-48a6-93f4-a47058e4783c
        property: N8N_ENCRYPTION_KEY
      secretKey: N8N_ENCRYPTION_KEY
      sourceRef:
        storeRef:
          name: vaultwarden-fields
          kind: ClusterSecretStore
    - remoteRef:
        key: 3819ee8a-d920-48a6-93f4-a47058e4783c
        property: TASK_RUNNER_TOKEN
      secretKey: TASK_RUNNER_TOKEN
      sourceRef:
        storeRef:
          name: vaultwarden-fields
          kind: ClusterSecretStore
