apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao-store
    kind: ClusterSecretStore
  target:
    creationPolicy: Owner
    name: n8n-secrets
    template:
      type: Opaque
      data:
        N8N_PROTOCOL: "https"
        N8N_HOST: "n8n.kerrlab.app"
        N8N_PORT: "5678"
        N8N_LICENSE_ACTIVATION_KEY: "{{ .N8N_LICENSE_ACTIVATION_KEY }}"
        QUEUE_BULL_REDIS_PASSWORD: "{{ .QUEUE_BULL_REDIS_PASSWORD }}"
        N8N_ENCRYPTION_KEY: "{{ .N8N_ENCRYPTION_KEY }}"
        TASK_RUNNER_TOKEN: "{{ .TASK_RUNNER_TOKEN }}"
  data:
    - secretKey: N8N_LICENSE_ACTIVATION_KEY
      remoteRef:
        key: automation/n8n
        property: N8N_LICENSE_ACTIVATION_KEY
    - secretKey: QUEUE_BULL_REDIS_PASSWORD
      remoteRef:
        key: automation/n8n
        property: QUEUE_BULL_REDIS_PASSWORD
    - secretKey: N8N_ENCRYPTION_KEY
      remoteRef:
        key: automation/n8n
        property: N8N_ENCRYPTION_KEY
    - secretKey: TASK_RUNNER_TOKEN
      remoteRef:
        key: automation/n8n
        property: TASK_RUNNER_TOKEN
