apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n-worker
  labels:
    app: n8n-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: n8n-worker
  template:
    metadata:
      labels:
        app: n8n-worker
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: n8n-worker
          image: docker.n8n.io/n8nio/n8n
          command:
            - /bin/sh
          args:
            - -c
            - sleep 5; n8n worker
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 2000m
              memory: 4Gi
          envFrom:
            - secretRef:
                name: n8n-db-credentials
          env:
            - name: EXECUTIONS_MODE
              value: "queue"
            - name: QUEUE_BULL_REDIS_HOST
              value: "redis-master.data-services.svc.cluster.local"
            - name: QUEUE_BULL_REDIS_PORT
              value: "6379"
            - name: DB_TYPE
              value: "postgresdb"
            - name: DB_POSTGRESDB_DATABASE
              value: "n8n"
            - name: DB_POSTGRESDB_HOST
              value: "fortress.kerrlab.app"
            - name: DB_POSTGRESDB_PORT
              value: "15432"
            - name: DB_POSTGRESDB_USER
              value: "n8n_user"
            - name: TZ
              value: "Europe/Chisinau"
            - name: N8N_PROTOCOL
              value: "https"
            - name: N8N_HOST
              value: "n8n.kerrlab.app"
            - name: WEBHOOK_URL
              value: "https://n8n.kerrlab.app"
            - name: N8N_PROXY_HOPS
              value: "1"
            - name: GENERIC_TIMEZONE
              value: "Europe/Chisinau"
