apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - http-route.yaml
  - network-policy.yaml
  - configmap.yaml
  - secret.yaml

labels:
  - pairs:
      app.kubernetes.io/name: bazarr
      app.kubernetes.io/part-of: media-services
images:
  - name: ghcr.io/home-operations/bazarr
    newTag: 1.6.0@sha256:cd63bbd0986c93e238eb8b9442604d249f0d4080099b389f822abe2062044417
