apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - http-route.yaml
  - network-policy.yaml
  - configmap.yaml
  - secret.yaml

labels:
  - pairs:
      app.kubernetes.io/name: bazarr
      app.kubernetes.io/part-of: media-services
images:
  - name: ghcr.io/home-operations/bazarr
    newTag: 1.6.2@sha256:17dc1cff22e99694ffbfb06555526cb47a66b362b4d6c982f06b557f7caae2bb
