apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - http-route.yaml
  - network-policy.yaml
  - configmap.yaml
  - secret.yaml

labels:
  - pairs:
      app.kubernetes.io/name: bazarr
      app.kubernetes.io/part-of: media-services
images:
  - name: ghcr.io/home-operations/bazarr
    newTag: 1.5.6@sha256:80cb090162b47ea1bfb499d742b45a460b282f17ffefa4c01d518a5c8d52a5a4
