apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: bazarr-policy
spec:
  endpointSelector:
    matchLabels:
      app: bazarr


  # ----=== Egress ===----
  egress:
    # === Allow access to services ===
    - toServices:
        - k8sService:
            serviceName: plex-ui
            namespace: media
        - k8sService:
            serviceName: qbittorrent-ui
            namespace: media
        - k8sService:
            serviceName: sonarr-ui
            namespace: media
        - k8sService:
            serviceName: radarr-ui
            namespace: media
        - k8sService:
            serviceName: ntfy
            namespace: automation
    # === Allow access to external for subtitles ===
    - toEntities:
        - "world"
