apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bazarr-external-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-store

  target:
    name: bazarr-secrets
    creationPolicy: Owner

  data:
    - secretKey: POSTGRES_USERNAME
      remoteRef:
        key: media/bazarr
        property: POSTGRES_USERNAME
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: media/bazarr
        property: POSTGRES_PASSWORD
    - secretKey: POSTGRES_HOST
      remoteRef:
        key: media/bazarr
        property: POSTGRES_HOST
    - secretKey: POSTGRES_PORT
      remoteRef:
        key: media/bazarr
        property: POSTGRES_PORT
