apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bazarr-external-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vaultwarden-fields

  target:
    name: bazarr-secrets
    creationPolicy: Owner

  data:
    - secretKey: POSTGRES_USERNAME
      remoteRef:
        key: 507cdc92-0bce-4b84-8712-9dcfd4d08370
        property: postgres_user
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: 507cdc92-0bce-4b84-8712-9dcfd4d08370
        property: postgres_password
    - secretKey: POSTGRES_HOST
      remoteRef:
        key: 507cdc92-0bce-4b84-8712-9dcfd4d08370
        property: postgres_host
    - secretKey: POSTGRES_PORT
      remoteRef:
        key: 507cdc92-0bce-4b84-8712-9dcfd4d08370
        property: postgres_port
