apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mosquitto-passwordfile-es
spec:
  target:
    name: mosquitto-passwordfile

  secretStoreRef:
    name: openbao-store
    kind: ClusterSecretStore

  data:
    - secretKey: password_key
      remoteRef:
        key: iot/mosquitto
        property: password_key
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mosquitto-credentials-es
spec:
  target:
    name: mosquitto-credentials

  secretStoreRef:
    name: openbao-store
    kind: ClusterSecretStore

  data:
    - secretKey: user
      remoteRef:
        key: iot/mosquitto
        property: user
    - secretKey: password
      remoteRef:
        key: iot/mosquitto
        property: password