apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: iot

labels:
  - pairs:
      app.kubernetes.io/name: mqtt

resources:
  - credentials.yaml
  - config.yaml
  - deployment.yaml
  - service.yaml
  - network-policy.yaml
images:
  - name: busybox
    newTag: 1.38@sha256:dc2d74b28e4cf8984fa52af1f39bc7c3d9c73760b41a74d629f5d11b1ab28616
  - name: eclipse-mosquitto
    newTag: 2.0.22@sha256:199ea8ef2e35ec2b1b37e59cfd1dbae538ed4dfa4a2251a121a52215a6248a21
