apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: crowdsec-bouncer-key
  namespace: traefik
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vaultwarden-fields
  target:
    creationPolicy: Owner
    name: crowdsec-bouncer-key
  data:
    - remoteRef:
        key: 6fea0a29-0215-471f-aa9e-80fcf773c62f
        property: LAPI_KEY
      secretKey: bouncer-key
