apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: crowdsec-bouncer-key
  namespace: traefik
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-store
  target:
    creationPolicy: Owner
    name: crowdsec-bouncer-key
  data:
    - remoteRef:
        key: platform/security/crowdsec
        property: bouncer-key
      secretKey: bouncer-key
