apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kerrlab-app-tls
  namespace: traefik
spec:
  secretName: kerrlab-app-tls
  issuerRef:
    name: zerossl-prod
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
    - "*.kerrlab.app"
  privateKey:
    algorithm: ECDSA
    size: 384
    rotationPolicy: Always
