apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"

namespace: traefik
helmCharts:
  - name: traefik
    repo: https://traefik.github.io/charts
    version: 41.4.0
    releaseName: traefik
    namespace: traefik
    valuesFile: values/traefik-config.yaml
    includeCRDs: true

resources:
  - dashboard-auth.yaml
  - bouncer-secret.yaml
  - services.yaml
  - gateways.yaml
  - network-policy.yaml
  - error-pages.yaml

images:
  - name: ghcr.io/tarampampam/error-pages
    newTag: 4.2.5@sha256:6d42b5d6e1a014fa2373e3587f9e85c25589a089fd5f6fc4f2a496858f5e365d

patches:
  - target:
      kind: Namespace
      name: traefik
    patch: |-
      - op: add
        path: /metadata/labels
        value:
          pod-security.kubernetes.io/audit: privileged
          pod-security.kubernetes.io/enforce: privileged
          pod-security.kubernetes.io/warn: privileged
