apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"

namespace: traefik
helmCharts:
  - name: traefik
    repo: https://traefik.github.io/charts
    version: 41.4.0
    releaseName: traefik
    namespace: traefik
    valuesFile: values/traefik-config.yaml
    includeCRDs: true

resources:
  - dashboard-auth.yaml
  - bouncer-secret.yaml
  - services.yaml
  - gateways.yaml
  - network-policy.yaml
  - error-pages.yaml
  - dragonfly.yaml

images:
  - name: ghcr.io/tarampampam/error-pages
    newTag: 3.4.1@sha256:fadd887eb57a9763198eb434bfddaa52a15a33b9a12c1cfb69304ca9fc4536d9
  - name: ghcr.io/dragonflydb/dragonfly
    newTag: v1.40.1@sha256:ebf3c6c213e82fb51b4521660cca13f06f3421dc5b1ed14f2f474c50b5e29986

patches:
  - target:
      kind: Namespace
      name: traefik
    patch: |-
      - op: add
        path: /metadata/labels
        value:
          pod-security.kubernetes.io/audit: privileged
          pod-security.kubernetes.io/enforce: privileged
          pod-security.kubernetes.io/warn: privileged
