apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: security

resources:
  - secrets.yaml
  - network-policy.yaml

helmCharts:
  - name: crowdsec
    repo: https://crowdsecurity.github.io/helm-charts
    version: 0.24.0
    releaseName: crowdsec
    namespace: security
    valuesFile: values.yaml

configMapGenerator:
  - name: crowdsec-config-template
    files:
      - config.yaml=templates/config.yaml
  - name: crowdsec-agent-config
    files:
      - config.yaml.local=templates/agent-config.yaml
