apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: crowdsec-secrets
  namespace: security
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-store
  target:
    creationPolicy: Owner
    name: crowdsec-secrets
  data:
    - remoteRef:
        key: security/crowdsec
        property: ENROLL_KEY
      secretKey: ENROLL_KEY
    - remoteRef:
        key: security/crowdsec
        property: LAPI_KEY
      secretKey: LAPI_KEY
    - remoteRef:
        key: security/crowdsec
        property: postgres_user
      secretKey: db-user
    - remoteRef:
        key: security/crowdsec
        property: postgres_password
      secretKey: db-password
    - remoteRef:
        key: security/crowdsec
        property: postgres_host
      secretKey: db-host
    - remoteRef:
        key: security/crowdsec
        property: postgres_port
      secretKey: db-port
    - remoteRef:
        key: security/crowdsec
        property: postgres_db
      secretKey: db-name
    - remoteRef:
        key: security/crowdsec
        property: UNIFI_BUN_KEY
      secretKey: UNIFI_BUN_KEY
    - remoteRef:
        key: security/crowdsec
        property: UNIFI_API_KEY
      secretKey: UNIFI_API_KEY
