apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: crowdsec-secrets
  namespace: security
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vaultwarden-fields
  target:
    creationPolicy: Owner
    name: crowdsec-secrets
  data:
    - remoteRef:
        key: 6fea0a29-0215-471f-aa9e-80fcf773c62f
        property: ENROLL_KEY
      secretKey: ENROLL_KEY
    - remoteRef:
        key: 6fea0a29-0215-471f-aa9e-80fcf773c62f
        property: LAPI_KEY
      secretKey: LAPI_KEY
    - remoteRef:
        key: 6fea0a29-0215-471f-aa9e-80fcf773c62f
        property: postgres_user
      secretKey: db-user
    - remoteRef:
        key: 6fea0a29-0215-471f-aa9e-80fcf773c62f
        property: postgres_password
      secretKey: db-password
    - remoteRef:
        key: 6fea0a29-0215-471f-aa9e-80fcf773c62f
        property: postgres_host
      secretKey: db-host
    - remoteRef:
        key: 6fea0a29-0215-471f-aa9e-80fcf773c62f
        property: postgres_port
      secretKey: db-port
    - remoteRef:
        key: 6fea0a29-0215-471f-aa9e-80fcf773c62f
        property: postgres_db
      secretKey: db-name
