apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: miniflux-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vaultwarden-fields
    kind: ClusterSecretStore
  target:
    name: miniflux-secrets
    creationPolicy: Owner
  data:
    # postgres://miniflux:secret@db/miniflux?sslmode=disable
    - secretKey: DATABASE_URL
      remoteRef:
        key: ""
        property: "DB_PASSWORD"
    - secretKey: ADMIN_USERNAME
      remoteRef:
        key: ""
        property: "ADMIN_USERNAME"
    - secretKey: ADMIN_PASSWORD
      remoteRef:
        key: ""
        property: "ADMIN_PASSWORD"
