apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: miniflux-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao-store
    kind: ClusterSecretStore
  target:
    name: miniflux-secrets
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: home/miniflux
        property: DATABASE_URL
    - secretKey: ADMIN_USERNAME
      remoteRef:
        key: home/miniflux
        property: ADMIN_USERNAME
    - secretKey: ADMIN_PASSWORD
      remoteRef:
        key: home/miniflux
        property: ADMIN_PASSWORD
