apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infrastructure-applications
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: strimzi-kafka-operator
  template:
    metadata:
      name: '{{name}}'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/vehkiya/homelab-k8s.git
        targetRevision: HEAD
        path: 'apps/infrastructure/{{name}}'
      destination:
        server: https://kube.kerrlab.app:6443
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
  syncPolicy:
    preserveResourcesOnDeletion: true
