apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: redis-ha-secret
  namespace: data-services
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vaultwarden-store
  target:
    name: redis-ha-secret
    template:
      engineVersion: v2
      data:
        redis-password: "{{ .redis_password }}"
  data:
    - secretKey: redis_password
      remoteRef:
        key: "1f0e063d-9fd0-482f-a69a-fc96cb8406cd"
        property: password
