apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: redis-policy
spec:
  endpointSelector:
    matchExpressions:
      - key: "k8s:app.kubernetes.io/name"
        operator: In
        values:
          - redis-ha
  # ----=== Ingress ===----
  ingress:
    # === Allow access from clients ===
    - fromEndpoints:
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": "security"
            "k8s:app": "authelia"
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": "security"
            "k8s:app": "oauth-proxy"
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": "home"
            "k8s:app": "bar-assistant"
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": "automation"
          matchExpressions:
            - key: "k8s:app"
              operator: In
              values:
                - n8n
                - n8n-worker
        - matchLabels:
            "k8s:app.kubernetes.io/name": "redis-ha-node"
        - matchLabels:
            "k8s:app.kubernetes.io/name": "redis-ha"
        - matchLabels:
            "k8s:name": "redis-operator"
      toPorts:
        - ports:
            - port: "6379"
              protocol: "TCP"
            - port: "26379"
              protocol: "TCP"
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: redis-operator-policy
spec:
  endpointSelector:
    matchLabels:
      "k8s:name": "redis-operator"
  # ----=== Egress ===----
  egress:
    - toEntities:
        - kube-apiserver
        - host
        - cluster
