apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: redis-policy
spec:
  endpointSelector:
    matchLabels:
      "k8s:app": redis
  # ----=== Ingress ===----
  ingress:
    # === Allow access from clients ===
    - fromEndpoints:
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": "security"
            "k8s:app": "authelia"
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": "security"
            "k8s:app": "oauth-proxy"
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": "home"
            "k8s:app": "bar-assistant"
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": "automation"
            "k8s:app": "n8n"
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": "automation"
            "k8s:app": "n8n-worker"
      toPorts:
        - ports:
            - port: "6379"
              protocol: "TCP"
