apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: data-services
helmCharts:
  - name: redis-operator
    repo: https://ot-container-kit.github.io/helm-charts/
    version: 0.23.0
    releaseName: redis-operator
    includeCRDs: true
