apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: iot

labels:
  - pairs:
      app.kubernetes.io/name: z2mqtt

resources:
  - network-policy.yaml
  - config.yaml
  - deployment.yaml
  - service.yaml
  - http-route.yaml
images:
  - name: busybox
    newTag: 1.37@sha256:0d3f1e630be52ade0c06107515937607be2cab11a2ad2122099fc79e19bcc18b
  - name: ghcr.io/koenkk/zigbee2mqtt
    newTag: 2.10.1@sha256:67c26dcf8346aced02fe1380a6afd1b57268bcef10faae3f6057c13d5d3dfa80
