apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: zigbee2mqtt-policy
spec:
  endpointSelector:
    matchLabels:
      app: zigbee2mqtt



  # ----=== Egress ===----
  egress:
    # === Allow access to services ===
    - toServices:
        - k8sService:
            serviceName: mosquitto-svc
            namespace: iot
    # === Allow traffic to the Zigbee Coordinator ===
    - toCIDR:
        - 192.168.4.36/32
      toPorts:
        - ports:
            - port: "6638"
              protocol: TCP