apiVersion: apps/v1
kind: Deployment
metadata:
  name: excalidraw
spec:
  selector:
    matchLabels:
      app: excalidraw
  template:
    metadata:
      labels:
        app: excalidraw
        networking/expose-web-ui: "true"
    spec:
      containers:
        - name: excalidraw
          image: excalidraw/excalidraw
          imagePullPolicy: "IfNotPresent"
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
          ports:
            - name: web-ui
              containerPort: 8080
