apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: excalidraw
spec:
  hosts:
    - excalidraw.kerrlab.app
  scaleTargetRef:
    name: excalidraw
    kind: Deployment
    apiVersion: apps/v1
    service: excalidraw-ui
    port: 8080
  replicas:
    min: 0
    max: 1
