apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tools
resources:
  - deployment.yaml
  - service.yaml
  - http-route.yaml
  - httpscaledobject.yaml
  - network-policy.yaml
images:
  - name: excalidraw/excalidraw
    newTag: latest@sha256:b6cd04431d88f2756a7c3095cf7970884e8fd6b2800c9445b5a60a5c715bbf0c
