apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: media
resources:
  - statefulset.yaml
  - service.yaml
  - http-route.yaml
  - network-policy.yaml
  - ntfy-credentials-secret.yaml
  - vpn-secret.yaml
  - qbit-secrets.yaml

configMapGenerator:
  - name: qbittorrent-scripts
    files:
      - notify-n8n.sh=templates/notify-n8n.sh
generatorOptions:
  disableNameSuffixHash: true

labels:
  - pairs:
      app.kubernetes.io/name: qbittorrent
      app.kubernetes.io/part-of: media-services
images:
  - name: alpine/k8s
    newTag: 1.36.0@sha256:c105e4eaa265c617e43be34fffc7d9961de76b65a1e520179ed61e2f3a9fabf7
  - name: ghcr.io/home-operations/qbittorrent
    newTag: 5.1.4@sha256:bb82ad6668f8eda1d0fcce6c1341498bfa879155bb1295cd9d314a2c35c07a01
  - name: ghcr.io/hononeko/qbit-ntfy-sidecar
    newTag: 1.0.0@sha256:4f67bb97cf5ecff4cd4b21c6a15fc24984c66b44dd6df782a325c31b4231c2df
  - name: qmcgaw/gluetun
    newTag: v3.41.1@sha256:1a5bf4b4820a879cdf8d93d7ef0d2d963af56670c9ebff8981860b6804ebc8ab
  - name: ghcr.io/hononeko/qbit-gluetun-sync
    newTag: 1.2.2@sha256:25b67f5d2ab5caaf677545728b2de18b75de0bf7a18f0a79f54022976298128b
