apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: media
resources:
  - statefulset.yaml
  - service.yaml
  - http-route.yaml
  - network-policy.yaml
  - ntfy-credentials-secret.yaml
  - vpn-secret.yaml
  - qbit-secrets.yaml

configMapGenerator:
  - name: qbittorrent-scripts
    files:
      - notify-n8n.sh=templates/notify-n8n.sh
generatorOptions:
  disableNameSuffixHash: true

labels:
  - pairs:
      app.kubernetes.io/name: qbittorrent
      app.kubernetes.io/part-of: media-services
images:
  - name: alpine/k8s
    newTag: 1.36.2@sha256:44ef4942e171939b9c665a4a84beb80e2dcdb9a24330d4651cfdfd2e9deecc47
  - name: ghcr.io/home-operations/qbittorrent
    newTag: 5.2.2@sha256:58e7ef6ed77f369c484b3066652c9e2e3d2c87bd44fce9883455565145fbd8eb
  - name: ghcr.io/hononeko/qbit-ntfy-sidecar
    newTag: 1.0.1@sha256:3aaa53c009f229b25eb7375814d2610fbf8eccf7b6eb7a651136105e2bf03352
  - name: ghcr.io/qdm12/gluetun
    newTag: v3.41.1@sha256:1a5bf4b4820a879cdf8d93d7ef0d2d963af56670c9ebff8981860b6804ebc8ab
  - name: ghcr.io/hononeko/qbit-gluetun-sync
    newTag: 1.2.3@sha256:6e9a9466e47022954cff6af054b3cbe4f08f09f38e2d6219d3dc3654c53501fb
