apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ntfy-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-store

  target:
    name: ntfy-credentials
    creationPolicy: Owner

  data:
    - secretKey: NTFY_USER
      remoteRef:
        key: media/ntfy
        property: NTFY_USER
    - secretKey: NTFY_PASS
      remoteRef:
        key: media/ntfy
        property: NTFY_PASS
