apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qbit-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao-store
    kind: ClusterSecretStore
  target:
    name: qbit-secrets
    creationPolicy: Owner
  data:
    - secretKey: WEBHOOK_SECRET
      remoteRef:
        key: media/qbittorrent
        property: WEBHOOK_SECRET
    - secretKey: WEBHOOK_ID
      remoteRef:
        key: media/qbittorrent
        property: WEBHOOK_ID
