apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gluetun-protonvpn-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao-store
    kind: ClusterSecretStore
  target:
    name: gluetun-secret
    creationPolicy: Owner
  data:
    - secretKey: WIREGUARD_PRIVATE_KEY
      remoteRef:
        key: media/gluetun
        property: WIREGUARD_PRIVATE_KEY
