apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - http-route.yaml
  - network-policy.yaml
  - secret.yaml

labels:
  - pairs:
      app.kubernetes.io/name: prowlarr
      app.kubernetes.io/part-of: media-services
images:
  - name: ghcr.io/home-operations/prowlarr
    newTag: 2.5.2@sha256:53b9cccebceab12825be1a22f2f9c2a2e8fa5e4c6a0aa78286fbe90a317fa070
  - name: ghcr.io/hononeko/k8s-config-tools
    newTag: 0.1.1@sha256:fb03e8e7910a51472309b361675f38da44ee398ab6ec64b020b660d4d0d4e400

configMapGenerator:
  - name: prowlarr-config-template
    files:
      - config.xml=templates/config.xml
generatorOptions:
  disableNameSuffixHash: true