apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - http-route.yaml
  - network-policy.yaml
  - secret.yaml

labels:
  - pairs:
      app.kubernetes.io/name: prowlarr
      app.kubernetes.io/part-of: media-services
images:
  - name: ghcr.io/home-operations/prowlarr
    newTag: 2.6.1@sha256:ce5d6bdd5be6529f503df77aa9d2bad20239031d7c660406e8fb1c6d621dd020
  - name: ghcr.io/hononeko/k8s-config-tools
    newTag: 0.1.1@sha256:fb03e8e7910a51472309b361675f38da44ee398ab6ec64b020b660d4d0d4e400

configMapGenerator:
  - name: prowlarr-config-template
    files:
      - config.xml=templates/config.xml
generatorOptions:
  disableNameSuffixHash: true