apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - http-route.yaml
  - network-policy.yaml
  - secret.yaml

labels:
  - pairs:
      app.kubernetes.io/name: prowlarr
      app.kubernetes.io/part-of: media-services
images:
  - name: ghcr.io/home-operations/prowlarr
    newTag: 2.3.4@sha256:4df82f58d39fde43a206c4bba126226b63ecf2394df202e94c31afc9faae3ed9
  - name: hairyhenderson/gomplate
    newTag: v5.0-alpine@sha256:e9f830456c24b92dc8f59591d9604c90af6b7102c503f9834e716eb1002440e9

configMapGenerator:
  - name: prowlarr-config-template
    files:
      - config.xml=templates/config.xml
generatorOptions:
  disableNameSuffixHash: true