apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prowlarr-external-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vaultwarden-fields

  target:
    name: prowlarr-secrets
    creationPolicy: Owner

  data:
    - secretKey: PROWLARR_API_KEY
      remoteRef:
        key: 4223c0f9-093f-48bc-9fd9-00cb87846924
        property: api_key
    - secretKey: POSTGRES_USER
      remoteRef:
        key: 4223c0f9-093f-48bc-9fd9-00cb87846924
        property: postgres_user
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: 4223c0f9-093f-48bc-9fd9-00cb87846924
        property: postgres_password
    - secretKey: POSTGRES_PORT
      remoteRef:
        key: 4223c0f9-093f-48bc-9fd9-00cb87846924
        property: postgres_port
    - secretKey: POSTGRES_HOST
      remoteRef:
        key: 4223c0f9-093f-48bc-9fd9-00cb87846924
        property: postgres_host
    - secretKey: POSTGRES_MAIN_DB
      remoteRef:
        key: 4223c0f9-093f-48bc-9fd9-00cb87846924
        property: postgres_main_db
    - secretKey: POSTGRES_LOG_DB
      remoteRef:
        key: 4223c0f9-093f-48bc-9fd9-00cb87846924
        property: postgres_log_db