apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prowlarr-external-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-store

  target:
    name: prowlarr-secrets
    creationPolicy: Owner

  data:
    - secretKey: PROWLARR_API_KEY
      remoteRef:
        key: media/prowlarr
        property: PROWLARR_API_KEY
    - secretKey: POSTGRES_USER
      remoteRef:
        key: media/prowlarr
        property: POSTGRES_USER
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: media/prowlarr
        property: POSTGRES_PASSWORD
    - secretKey: POSTGRES_PORT
      remoteRef:
        key: media/prowlarr
        property: POSTGRES_PORT
    - secretKey: POSTGRES_HOST
      remoteRef:
        key: media/prowlarr
        property: POSTGRES_HOST
    - secretKey: POSTGRES_MAIN_DB
      remoteRef:
        key: media/prowlarr
        property: POSTGRES_MAIN_DB
    - secretKey: POSTGRES_LOG_DB
      remoteRef:
        key: media/prowlarr
        property: POSTGRES_LOG_DB