apiVersion: apps/v1
kind: Deployment
metadata:
  name: bentopdf
spec:
  selector:
    matchLabels:
      app: bentopdf
  template:
    metadata:
      labels:
        app: bentopdf
        networking/expose-web-ui: "true"
    spec:
      containers:
        - name: bentopdf
          image: ghcr.io/alam00000/bentopdf-simple
          ports:
            - name: web-ui
              containerPort: 8080
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /
              port: web-ui
            initialDelaySeconds: 5
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: web-ui
            initialDelaySeconds: 1
            periodSeconds: 10
          securityContext:
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: nginx-cache
              mountPath: /var/cache/nginx
            - name: nginx-run
              mountPath: /var/run
            - name: nginx-tmp
              mountPath: /etc/nginx/tmp
            - name: tmp
              mountPath: /tmp
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - name: nginx-cache
          emptyDir: { }
        - name: nginx-run
          emptyDir: { }
        - name: nginx-tmp
          emptyDir: { }
        - name: tmp
          emptyDir: { }
