apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - http-route.yaml
  - external-http-route.yaml
  - rate-limit.yaml
  - httpscaledobject.yaml
  - network-policy.yaml

images:
  - name: ghcr.io/alam00000/bentopdf-simple
    newTag: 2.8.7@sha256:ba67d44f07ec0d2d636c945eef1c186f71bceda3d11b1e9809d7dbfbbaaacfa4
