apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - http-route.yaml
  - external-http-route.yaml
  - rate-limit.yaml
  - httpscaledobject.yaml
  - network-policy.yaml

images:
  - name: ghcr.io/alam00000/bentopdf-simple
    newTag: 2.8.6@sha256:1a947a9d4ae515be27b381a2a1f8565d5fa33087c32abc2bb7a6754f83e95f4c
