apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wedding-share-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao-store
    kind: ClusterSecretStore
  target:
    name: wedding-share-credentials
    creationPolicy: Owner
  data:
    - secretKey: ACCOUNT_OWNER_USERNAME
      remoteRef:
        key: home/wedding-share
        property: ACCOUNT_OWNER_USERNAME
    - secretKey: ACCOUNT_OWNER_PASSWORD
      remoteRef:
        key: home/wedding-share
        property: ACCOUNT_OWNER_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wedding-share-keys
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao-store
    kind: ClusterSecretStore
  target:
    name: wedding-share-keys
    creationPolicy: Owner
  data:
    - secretKey: ENCRYPTION_KEY
      remoteRef:
        key: home/wedding-share
        property: ENCRYPTION_KEY
    - secretKey: ENCRYPTION_SALT
      remoteRef:
        key: home/wedding-share
        property: ENCRYPTION_SALT