apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fluxer-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao-store
    kind: ClusterSecretStore
  target:
    name: fluxer-secrets
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: media/fluxer
        property: POSTGRES_PASSWORD
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: media/fluxer
        property: REDIS_PASSWORD
    - secretKey: FLUXER_S3_ACCESS_KEY
      remoteRef:
        key: media/fluxer
        property: FLUXER_S3_ACCESS_KEY
    - secretKey: FLUXER_S3_SECRET_KEY
      remoteRef:
        key: media/fluxer
        property: FLUXER_S3_SECRET_KEY
    - secretKey: LIVEKIT_API_KEY
      remoteRef:
        key: media/fluxer
        property: LIVEKIT_API_KEY
    - secretKey: LIVEKIT_API_SECRET
      remoteRef:
        key: media/fluxer
        property: LIVEKIT_API_SECRET
    - secretKey: FLUXER_SUDO_MODE_SECRET
      remoteRef:
        key: media/fluxer
        property: FLUXER_SUDO_MODE_SECRET
    - secretKey: FLUXER_CONNECTION_INITIATION_SECRET
      remoteRef:
        key: media/fluxer
        property: FLUXER_CONNECTION_INITIATION_SECRET
    - secretKey: FLUXER_VAPID_PUBLIC_KEY
      remoteRef:
        key: media/fluxer
        property: FLUXER_VAPID_PUBLIC_KEY
    - secretKey: FLUXER_VAPID_PRIVATE_KEY
      remoteRef:
        key: media/fluxer
        property: FLUXER_VAPID_PRIVATE_KEY
    - secretKey: FLUXER_GATEWAY_RPC_AUTH_TOKEN
      remoteRef:
        key: media/fluxer
        property: FLUXER_GATEWAY_RPC_AUTH_TOKEN
    - secretKey: FLUXER_MEDIA_PROXY_SECRET_KEY
      remoteRef:
        key: media/fluxer
        property: FLUXER_MEDIA_PROXY_SECRET_KEY
    - secretKey: FLUXER_MEDIA_PROXY_UPLOAD_RELAY_SECRET_BASE64
      remoteRef:
        key: media/fluxer
        property: FLUXER_MEDIA_PROXY_UPLOAD_RELAY_SECRET_BASE64
    - secretKey: FLUXER_ADMIN_SECRET_KEY_BASE
      remoteRef:
        key: media/fluxer
        property: FLUXER_ADMIN_SECRET_KEY_BASE
    - secretKey: FLUXER_ADMIN_OAUTH_CLIENT_SECRET
      remoteRef:
        key: media/fluxer
        property: FLUXER_ADMIN_OAUTH_CLIENT_SECRET
    - secretKey: MEILI_MASTER_KEY
      remoteRef:
        key: media/fluxer
        property: MEILI_MASTER_KEY
