apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: sonarr
  name: sonarr-anime-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: longhorn
  volumeMode: Filesystem
